// PRIMA 紋戦 — 言語（English・中文・한국어）
// 日本語が元の言葉。ここには訳だけを置く。game.js が起動時に選んだ言語の data を PRIMA_DATA に重ね、ui で画面の文を訳す。
//   ui   ：日本語の文をキーにした訳。{0} {1}… は game.js が差し込む値
//   data ：PRIMA_DATA に重ねる訳（術・現象・流派・台詞・遊び方など）。配列の中のオブジェクトは同じ位置のものに重なる
// 新しい文を画面に足したら、ここの3つの言語にも訳を足す（scripts/smoke.cjs が抜けを調べる）
(() => {
const LANG = {};

// ═══ English ═══════════════════════════════════════════════════
LANG.en = {
  ui: {
    '・': ' · ', '！': '!', '／': ' / ', '{0}{1}。': '{0} {1}. ',
    '加速': 'Haste', '硬化': 'Harden', '活性': 'Vitality', '自分の紋の魔力を体へ書き込んだ': 'You inscribed your own crest\'s mana into your body',
    '暴発': 'Misfire', '「{0}」は制御容量を超えていた': '"{0}" exceeded your control capacity', '術式が…崩れる！': 'The spell… is collapsing!',
    '結界崩壊': 'Ward shattered', '貫通': 'Pierce', '剥離': 'Strip', '「{0}」の節点': 'Node of "{0}"',
    '{0}を含む術が強まり（威力 ×{1}・消費 ×{2}）、輪の中では魔力が湧き出る': 'Spells with {0} grow stronger (power ×{1}, cost ×{2}), and mana wells up inside the ring',
    '要の陣': 'Keystone Circle', 'ここに立つ間は制御容量が +{0}。重い術を暴発させずに扱える': 'Control capacity +{0} while you stand here. Heavy spells won\'t misfire',
    '共鳴': 'Resonance', '相殺': 'Cancel', '融合': 'Fusion', '魔装': 'Imbue', '誘爆': 'Chain blast',
    '完全結界が解けた': 'Perfect Ward dissolved', '魔力が尽きた': 'Out of mana', '術を唱えると解ける': 'Casting a spell dissolves it',
    '+{0} 魔力': '+{0} mana', '糸が切れた': 'Thread snapped', '術者から離れすぎた': 'Too far from the caster', '糸を断たれた': 'Your thread was cut',
    '回収 +{0} 魔力': 'Recalled +{0} mana', '糸でつながった術式 {0} つをほどいた': 'Unraveled {0} threaded spells', '構造崩壊': 'Structure broken',
    '{0} を散らした': 'You scattered {0}', '+{0} 魔素': '+{0} essence',
    '制御容量が {0} になった。より重い術を安定して放てる': 'Control capacity is now {0}. Heavier spells are stable',
    '次の制御容量まで育て': 'Keep growing toward the next capacity', '曲を変えた': 'Track changed',
    '声なし': 'No voice', '技名だけ': 'Spell names', '技名と叫び': 'Names & cries', '声：{0}': 'Voice: {0}',
    '要の陣 ― 制御容量 +{0}': 'Keystone Circle — control capacity +{0}',
    '{0}の節点 ― {0}の術が強まり、魔力が湧く': 'Node of {0} — {0} spells grow stronger, mana wells up',
    '{0}人': '{0}', 'LV {0}・制御容量 {1}': 'LV {0} · Capacity {1}', '（LV{0}で{1}）': ' ({1} at LV{0})',
    '魔力 {0}': 'Mana {0}', '部品 {0}/{1}': 'Parts {0}/{1}', '・暴発 {0}%': ' · Misfire {0}%',
    '糸 {0}': 'Threads {0}', 'F 指示起爆（{0}）': 'F Detonate ({0})', 'G 回収': 'G Recall',
    '与えた威力 {0}・毎秒 {1}': 'Dealt {0} · {1}/s', '受けた威力 {0}・防いだ {1}': 'Taken {0} · Blocked {1}',
    '攻撃人形：撃つ': 'Attack dummies: ON', '攻撃人形：止める': 'Attack dummies: OFF',
    '{0} に散らされた': 'Scattered by {0}', '結界の外で散った': 'Scattered outside the ward', '{0} が結界に散った': '{0} was scattered',
    '攻撃人形が撃ちはじめた': 'The attack dummies opened fire', '攻撃人形を止めた': 'Attack dummies stopped',
    '受けた威力と、結界で防いだ数を数える（修練場では散らない）': 'Counts damage taken and hits blocked by wards (you can\'t fall in the training hall)',
    '技': 'Nm', '声': 'Vo', '声：{0}（V で切り替え）': 'Voice: {0} (V to switch)',
    '自動（ブラウザに合わせる）': 'Auto (match browser)', '　◆自然': '  ◆natural', '（日本語の声が見つからない）': '(No voice found for this language)',
    '首位　{0}　{1}': 'Leader  {0}  {1}', '次の「{0}」まで {1} pt': '{1} pt to "{0}"', '最上位の位階': 'Highest rank',
    '{0}位': '#{0}', '撃破 {0}': 'Kills {0}', '<li class="empty">まだ入場していない</li>': '<li class="empty">No battles yet</li>',
    '部品 {0}・魔力 {1}': 'Parts {0} · Mana {1}', '原理負荷 {0}': 'Principle load {0}', 'なし': 'None',
    '単一原理（純放出）。最も軽く速い': 'Single principle (pure release). Lightest and fastest',
    '負荷 {0}・半径 {1}': 'Load {0} · Radius {1}', '自動': 'Auto', '広がり方から決める（弾は針、細い波は結晶、ほかは球）': 'Chosen from the spread (bolt: needle, thin wave: shard, others: orb)',
    '{0}（速さ×{1}・当たり×{2}・威力×{3}・結界へ×{4}{5}）': '{0} (speed ×{1}, hitbox ×{2}, power ×{3}, vs wards ×{4}{5})', '・形作る負荷 {0}': ', shaping load {0}',
    '作例「{0}」を {1} に読み込んだ': 'Loaded example "{0}" into slot {1}',
    '流派「{0}」の4つの術を読み込んだ（{1}）': 'Loaded the four spells of the "{0}" school ({1})',
    '{0}の「{1}」を {2} に読み込んだ': 'Loaded {0}\'s "{1}" into slot {2}', '初期の4つに戻した': 'Reset to the starting four',
    'まっすぐ飛ばす': 'fire it straight', '放ち、違う紋の大きな魔力へ曲がらせる': 'release it to curve toward large foreign mana',
    '放物線で狙った地点へ落とす': 'lob it onto the target point', '足元近くへ転がして止める': 'roll it near your feet to settle',
    '自分の足元に置く': 'place it at your feet', '自分の周りに纏う': 'wrap it around yourself', '三方へ撃ち分ける': 'fire it three ways',
    '一直線の光にして貫く': 'pierce with a straight line of light',
    '触れた瞬間に': 'On contact, it', '殻が割れる時（時限）に': 'When its shell breaks (timer), it', '違う紋が近づいた時に': 'When a foreign crest comes near, it', 'F の合図で': 'On your F signal, it',
    '一度作用する': 'acts once', '大きく炸裂する': 'bursts widely', '追尾する小片に分かれる': 'splits into homing shards',
    'その場に領域として残る': 'lingers as a field', '攻撃せずに魔力の粒と囮を撒く': 'scatters mana motes and a decoy without attacking',
    '領域の中の敵から魔力と魔素を奪い続ける': 'keeps draining mana and essence from foes inside the field',
    '強化術：自分の紋の魔力を体へ書き込み、{0}。': 'Enhancement: inscribes your crest\'s mana into your body and {0}.',
    '動きを速くする（加速）': 'speeds you up (Haste)', '受ける威力を減らす（硬化）': 'reduces damage taken (Harden)', '体力を少しずつ戻す（活性）': 'slowly restores health (Vitality)',
    '完全：固体とエネルギーを重ね、どちらの質も光線も通さない。引き換えに、張っている間は魔力が戻らず毎秒減り、足が重く、術を唱えると解ける。': 'Perfect: layers solid and energy so nothing passes, not even beams. In exchange, while it stands your mana drains every second, you move slowly, and casting dissolves it.',
    '{0}枚の城壁で自分をぐるりと囲む（ほとんど回らない）。弾を受け止める壁になる': 'surround yourself with {0} castle walls (they barely turn), a wall that catches shots',
    '{0}本の{1}を自分の周りに回らせる。弾を受け止め、触れた相手を斬る': 'spin {0} {1}s around yourself; they catch shots and cut whoever touches them',
    '刃': 'blade', '「{0}」を固体にして、{1}。': 'Solidify "{0}" and {1}. ',
    'エネルギーの弾は貫いてくる。エネルギーの結界は剥がせる。': 'Energy shots pierce through. Energy wards can be stripped. ',
    '糸でつながり、回収（G）できる。': 'Threaded: can be recalled (G). ', '「{0}」を{1}。': '"{0}": {1}. ',
    '{0}の「{1}」を{2}{3}。': '{0} "{1}" — {2}{3}. ', '固体（結晶）にして': 'solidified into crystal, ', 'エネルギーのまま': 'as raw energy, ',
    '周りに入った違う紋に{0}。': 'Against foreign crests in range, it {0}. ', '作用し続ける': 'keeps acting',
    '固体の結界には止められるが、エネルギーの結界は剥がせる。': 'Stopped by solid wards, but strips energy wards. ',
    '固体の結界は貫けるが、エネルギーの結界には止められる。': 'Pierces solid wards, but is stopped by energy wards. ',
    '六枚の面の壁で囲む城壁になる。': 'Becomes a six-sided castle wall. ', '一枚の面の壁になる。': 'Becomes a single flat wall. ', '形：{0}。': 'Shape: {0}. ',
    '放った後も糸でつながり、誘導・指示起爆（F）・回収（G）ができる（維持費がかかる）。': 'Stays threaded after release: guide it, detonate (F), recall (G). Upkeep applies. ',
    '追加性質：{0}。': 'Extra traits: {0}. ',
    '貫通光線は「細い波・接触・単発・糸：切断」で固定': 'Piercing Ray is fixed to thin wave, contact, single, thread cut',
    '貫通光線は光そのもの。質は「エネルギー」だけ': 'A Piercing Ray is pure light: energy only',
    '完全は結界を作る術（固化・物性編壁・掘削塹壕・根絡・位相牢・重縛結界・位相転換・反力変換）と周回にだけ使える': 'Perfect only works on ward-making spells (Solidify, Matter Wall, Trench, Rootbind, Phase Prison, Bulwark Ward, Phase Inversion, Counterforce) and orbit',
    '周回は常に起動しているので「接触」だけ': 'Orbit is always active: contact only', '周回の追加機能は「単発・残留・吸魔」だけ': 'Orbit only allows single, linger, siphon',
    '指示起爆は糸を通して合図を送るので「維持」が必要': 'Command detonation signals through a thread: hold is required',
    '部品 {0}': 'Parts {0}', '{0}（押すと外す）': '{0} (click to remove)', 'なし（最大{0}つ・重複可）': 'None (up to {0}, repeats allowed)',
    '現象：{0}': 'Phenomenon: {0}', '{0}秒': '{0}s', '純度 ×{0}（部品が少ないほど重い）': 'Purity ×{0} (fewer parts hit harder)',
    'LV{0}〜 容量{1}': 'LV{0}+ capacity {1}', '・安定': ' · stable', '決定して試す': 'Confirm & try', '修練場で試す': 'Try in the training hall',
    '糸{0}': 'Thread: {0}', '名無し': 'Nameless', '人形を相手に術を試す。T で術式台、Esc で戻る': 'Test spells on dummies. T: spell forge, Esc: back',
    '術を放つと入場保護が解ける': 'Casting ends your entry shield', '左をなぞって歩く': 'Drag left to walk', '右をタッチして放つ': 'Tap right to cast',
    '下の枠で持ち替え': 'Switch spells below', '左クリック': 'Left click', '放つ': 'Cast', '持ち替え': 'Switch', '回避': 'Dodge', '退出': 'Leave',
    '歩く': 'Walk', '魔導士を動かしてみよう。': 'Move your mage.', '矢印キー': 'Arrow keys', '画面の左半分をなぞる': 'Drag on the left half',
    '術を放つ': 'Cast a spell',
    'マウスで狙い、左クリックで術を放つ。押し続けると続けて唱える。放つたびに魔力（青い帯）を使う。戦場では魔力は勝手に戻らず、光の粒（魔素）を拾うと戻る。': 'Aim with the mouse and left-click to cast. Hold to keep casting. Each cast spends mana (blue bar). On the battlefield mana does not refill by itself: collect the glowing motes (essence) to restore it.',
    'マウスで狙う': 'Aim with mouse', '画面の右半分をタッチ': 'Tap the right half', '人形に当てる': 'Hit a dummy',
    '近くの人形に術を当てよう。当てた威力は上の「与えた威力」に出る。': 'Hit a nearby dummy. Your damage shows in "Dealt" at the top.', '人形の方をタッチ': 'Tap toward a dummy',
    '術を持ち替える': 'Switch spells', '術は4つまで持てる。2〜4に持ち替えて放ってみよう。4の「物性編壁」は相手の術を止める壁になる。': 'You carry four spells. Switch to 2–4 and cast. Slot 4, "Matter Wall", raises a wall that stops enemy spells.',
    'ホイール': 'Wheel', '下の枠をクリック': 'Click a slot below', '下の枠をタッチ': 'Tap a slot below',
    '一瞬だけ素早く跳んで、飛んでくる術をかわす（魔力を少し使う）。': 'Dash for an instant to evade incoming spells (costs a little mana).', '右クリック': 'Right click', '回避ボタン': 'Dodge button',
    '術を組む': 'Build a spell', '術式台で原理と部品をつないで、自分の術を作る。名前を付けると、放つときにその技名を叫ぶ。開いて「決定」で閉じよう。': 'Connect principles and parts in the spell forge to make your own spell. Name it and you\'ll shout the name when you cast. Open it, then close with "Confirm".',
    'T で術式台': 'T: spell forge', '決定 / Esc': 'Confirm / Esc', '上の「術式台」ボタン': 'The "Spell forge" button at the top', '準備はできた': 'You\'re ready',
    '戦場では地面の魔素を拾うと育ち、相手を散らすとその魔素を奪える。育つほど制御容量が増え、重い術も暴発させずに扱える。装いも格が上がる。魔力は光の粒を拾うと戻る。散ったらすぐ入りなおせる。': 'On the battlefield you grow by collecting essence, and scattering foes lets you claim theirs. Growth raises control capacity so heavy spells won\'t misfire, and your attire gains rank. Mana returns as you collect motes. If you fall, jump right back in.',
    '修練場に残る': 'Stay in the training hall', '手ほどきを終える': 'End tutorial', '結界の外で構造が崩れた': 'Your structure collapsed outside the ward',
    '{0}・計 {1} pt': '{0} · total {1} pt', '表示で問題が起きた': 'A display problem occurred', 'このまま遊べるが、続くときは再読み込みしてほしい': 'You can keep playing; reload if it continues',
    '光のにじみを切った': 'Bloom turned off', '動きが重かったため。設定で戻せる': 'Because things were slow. You can re-enable it in Settings',
    'PRIMA 紋戦': 'PRIMA: Crest War', 'このゲームは JavaScript で動きます。ブラウザの設定で JavaScript を有効にしてください。': 'This game needs JavaScript. Please enable it in your browser settings.',
    '魔素': 'Essence', '撃破': 'Kills', '一の間': 'First Hall', '手ほどき': 'Tutorial', '戦場へ入る': 'Enter the battlefield', '構造': 'Structure', '魔力': 'Mana',
    '避': 'Dg', '修練場': 'Training Hall', '与えた威力 0': 'Dealt 0', '受けた威力 0・防いだ 0': 'Taken 0 · Blocked 0', '術式台': 'Spell forge', 'ロビーへ': 'Lobby',
    '音': 'SE', '曲': 'BGM', '設': 'Set', '紋戦': 'Crest War', '原理を接続して術を組み、乱戦で放て。': 'Wire principles into spells. Unleash them in the melee.',
    'はじめての方へ': 'New here?', '修練場で、動き方・術の放ち方・術の組み方を実際にやってみる（3分ほど）。': 'Learn to move, cast and build spells hands-on in the training hall (about 3 minutes).',
    '手ほどきを始める': 'Start tutorial', '名前': 'Name', '光の色': 'Light color', '紋': 'Crest', '丸': 'Ring', 'ルーム': 'Room',
    '戦場の参加者はいまはBotです。オンライン対戦は準備中。': 'Other mages are bots for now. Online play is in preparation.',
    '遊び方': 'How to play', '設定（声・音・画面）': 'Settings (voice, sound, display)', '術': 'Spells', '術式台を開く': 'Open spell forge',
    '勝利宣言': 'Victory line', '倒したときに叫ぶ': 'Shouted when you scatter a foe', '断末魔': 'Last words', '散ったときに叫ぶ': 'Shouted when you fall', '声で試す': 'Test voice',
    '無': '無', '無紋': 'Crestless', '次の位階まで 250 pt': '250 pt to next rank', '最高魔素': 'Best essence', '最高順位': 'Best place', '通算撃破': 'Total kills',
    '入場': 'Battles', '最近の入場': 'Recent battles', '散った': 'Scattered', '生存': 'Survived', '位階が上がった': 'Rank up', 'もう一度入る': 'Enter again', '術式を組み直す': 'Rebuild spells',
    '原理と部品を接続して、1〜4 の枠に術を組む。部品が増えるほど消費と詠唱が重くなり、制御容量を超えると暴発しうる。': 'Connect principles and parts to build spells in slots 1–4. More parts mean more cost and longer chants; exceeding control capacity risks misfire.',
    '決定': 'Confirm', '何が起こる': 'What happens', '主原理': 'Main principle', 'もう一つの性質': 'Second nature', '副原理': 'Sub principle', '形': 'Shape', '広がり方': 'Spread',
    'どう届く': 'How it travels', '届き方': 'Delivery', 'いつ起こる': 'When it fires', '発動': 'Trigger', '起きた後': 'Afterward', '追加機能': 'Effect',
    '放った後': 'After release', '糸': 'Thread', '上乗せ': 'Extras', '追加性質': 'Extra traits', '強': 'Pw', '強弱': 'Strength', '威力': 'Power', '時限・持続': 'Timer / duration',
    '連射': 'Burst', '質': 'Mt', '固めるか': 'Matter', '固体／エネルギー': 'Solid / energy', '刃の形': 'Form', '速さ・当たり・衰え': 'Speed, hitbox, falloff',
    '空欄なら現象の名前。付けると放つときに唱える': 'Blank uses the phenomenon\'s name. A name is shouted when you cast', '魔弾針': 'Arcane Bolt Needle',
    '部品': 'Parts', '詠唱': 'Chant', '遠くで': 'At range', '制御容量と暴発': 'Control capacity & misfire', '部品にふれると、その意味がここに出る': 'Hover a part to see what it does',
    '達人の流派': 'Master schools', 'Bot が修める4つの術を丸ごと読み込む': 'Load all four spells a bot school uses', '達人の術': 'Master spells', '作例': 'Examples',
    '初期の4つに戻す': 'Reset to starting four', '六原理（単一原理で放つと）': 'Six principles (cast alone)', '閉じる': 'Close', '設定': 'Settings', '言語': 'Language',
    '名前を付けた術を放つとき、その技名を叫ぶ。「技名と叫び」は勝利宣言と断末魔も声に出す。': 'Shouts the name of a named spell when you cast. "Names & cries" also voices victory lines and last words.',
    '声の種類': 'Voice', '試す': 'Test', '「Natural」「Online」と付いた声がいちばん人に近い（Edge・Chrome で使える）。': 'Voices labeled "Natural" or "Online" sound most human (Edge, Chrome).',
    '効果音': 'Sound effects', '音楽': 'Music', '曲を変える': 'Change track', '光のにじみ': 'Bloom', '術の光がまわりへにじむ。重いときは切る': 'Spell light bleeds outward. Turn off if slow',
    '原理を接続して自分の術を組み、ルームの乱戦で放つ。魔素を拾い、散らして奪い、散ったらすぐ入りなおす魔法の乱戦。': 'Wire principles into your own spells and unleash them in a room-wide melee. Collect essence, scatter rivals to take theirs, and jump back in when you fall.',
    'PRIMA 紋戦 — 術を組み、乱戦で放て': 'PRIMA: Crest War — build spells, unleash them in the melee',
    '原理をつないで自分だけの魔法を組み、魔導士の乱戦で放つブラウザゲーム。登録不要・すぐ遊べる。': 'A browser game where you wire principles into your own magic and unleash it in a battle of mages. No sign-up, play instantly.',
    '戦場': 'Battlefield', '自分の状態': 'Your status', '順位': 'Ranking', '体と刻印': 'Body', '回避（右クリック / Space）': 'Dodge (right click / Space)',
    '射（槍・魔弾・日本刀・手裏剣）と砲（光線・斧）の人形が撃ってくる': 'Shooter (spear, bolt, katana, shuriken) and cannon (beam, axe) dummies attack you',
    '全体図': 'Map', '効果音（M）': 'Sound effects (M)', '音楽（N）': 'Music (N)', '声（V）': 'Voice (V)', 'ロビーへ戻る（Esc）': 'Back to lobby (Esc)',
    '術と叫び': 'Spells & cries', '位階': 'Rank', '術の枠': 'Spell slots', '術の動きの見本': 'Spell preview', '（自動）': '(auto)'
  },
  data: {
    naming: { join: ' ', extraSep: ' · ', beam: '{0} Piercing Ray', beamStrip: ' Blade',
      shapeSuffix: { needle: 'Needle', orb: 'Orb', shard: 'Shard', arrow: 'Arrow', blade: 'Sword', katana: 'Katana', scythe: 'Scythe', axe: 'Axe', hammer: 'Hammer', shuriken: 'Star', chakram: 'Chakram', spear: 'Spear', castle: 'Castle' } },
    principles: { motion: { name: 'Motion' }, bind: { name: 'Binding' }, divide: { name: 'Division' }, convert: { name: 'Conversion' }, grow: { name: 'Growth' }, phase: { name: 'Phase' } },
    noPrinciple: { name: 'None' },
    forms: { point: { name: 'Small bolt', suffix: 'Needle' }, line: { name: 'Thin wave', suffix: 'Pulse' }, plane: { name: 'Wall', suffix: 'Wall' }, ring: { name: 'Ring', suffix: 'Ring' }, field: { name: 'Wide field', suffix: 'Field' } },
    behaviors: {
      project: { name: 'Fire', note: 'Flies straight. Blocked by rocks and wards. Loses power with distance' },
      homing: { name: 'Homing', note: 'Curves toward large foreign mana. Hold the thread to steer it to your aim' },
      lob: { name: 'Lob', note: 'Arcs over wards and rocks. The landing point is telegraphed' },
      sow: { name: 'Sow', note: 'Scatters a seed near you. It rolls to a stop and becomes a trap' },
      drop: { name: 'Here', note: 'Placed where you stand' },
      orbit: { name: 'Orbit', note: 'Follows you and is always active. Single principle = enhancement. Solid = blades circle you' },
      relay: { name: 'Fan', note: 'Fires three ways. Dissipates quickly' },
      beam: { name: 'Piercing Ray', note: 'A high-power ray that pierces foes and barely fades with range. Pierces solid wards; shatters energy wards if strong enough' }
    },
    triggers: {
      contact: { name: 'Contact', note: 'Fires on hit or touch' }, fuse: { name: 'Timer', note: 'Fires when its shell breaks (fired shots burst at the aim point)' },
      proximity: { name: 'Sense', note: 'Fires when a foreign crest enters range. A stopped spell becomes a trap' }, command: { name: 'Command', note: 'Fires on your signal through the thread (F). Thread is held automatically' }
    },
    deploys: {
      single: { name: 'Single', note: 'Acts once according to its spread' }, burst: { name: 'Burst', note: 'Widens and bursts in an instant' },
      scatter: { name: 'Scatter', note: 'Splits into homing shards' }, linger: { name: 'Linger', note: 'The field lingers for a long time' },
      sprinkle: { name: 'Sprinkle', note: 'No attack: scatters its cost as mana motes anyone can collect; also a decoy for homing' },
      siphon: { name: 'Siphon', note: 'Drains mana and essence from foes in the field and pulls essence to you. Power halved' }
    },
    links: { cut: { name: 'Cut', note: 'The thread is cut on release. No upkeep. It only does what it was built to do' }, hold: { name: 'Hold', note: 'Stays threaded. Costs upkeep, but can be guided, detonated (F), extended and recalled (G)' } },
    extraEffects: { motion: { note: 'adds knockback on hit' }, bind: { note: 'slows on hit; two stacks briefly root' }, divide: { note: 'strips wards and shells, +8% power' }, convert: { note: 'steals mana on hit' }, grow: { note: 'spawns homing shards on hit' }, phase: { note: 'resists reduction from wards and Harden' } },
    matters: {
      energy: { name: 'Energy', note: 'Released as light and heat. Fast but fades at range. Pierces solid wards; stopped by energy wards' },
      solid: { name: 'Solid', note: 'Hardened into crystal. Slow but heavy and holds its power. Strips energy wards; stopped by solid wards. Solid wards are very tough' },
      perfect: { name: 'Perfect', note: 'Layers solid and energy into a perfect ward that stops everything. Very costly: mana drains while it stands, you move slowly, and casting dissolves it (wards and orbit only)' }
    },
    shapes: {
      needle: { name: 'Needle', note: 'Thin and fast. Small hitbox' }, orb: { name: 'Orb', note: 'Large and easy to land, slightly slow' }, shard: { name: 'Shard', note: 'A pointed crystal. Slightly better against wards' },
      arrow: { name: 'Arrow', note: 'The fastest, thinnest shot. Tiny hitbox, long reach' }, blade: { name: 'Sword', note: 'A broad straight blade. Big and heavy hits, dulls at range' },
      katana: { name: 'Katana', note: 'A curved blade that cuts through one foe to reach the next' }, scythe: { name: 'Scythe', note: 'A great arcing blade. Widest hitbox, sweeps up to three foes, short range' },
      axe: { name: 'Axe', note: 'A heavy axe. Slow but hits hard and smashes wards' }, hammer: { name: 'Hammer', note: 'A giant hammer. Strongest against wards; sends foes flying' },
      shuriken: { name: 'Shuriken', note: 'A spinning four-bladed star. Ricochets off rocks and wards twice' }, chakram: { name: 'Chakram', note: 'A spinning ring that flies out and returns to your hand, hitting on the way back' },
      spear: { name: 'Spear', note: 'A long point. Holds power best and pierces wards strongly' }, castle: { name: 'Castle', note: 'Stone ramparts. Fired: a slow heavy block. Orbited: castle walls surround you, barely turning' }
    },
    visualShapes: { auto: 'Auto', needle: 'Needle', orb: 'Orb', shard: 'Shard', arrow: 'Arrow', blade: 'Sword', katana: 'Katana', scythe: 'Scythe', axe: 'Axe', hammer: 'Hammer', shuriken: 'Shuriken', chakram: 'Chakram', spear: 'Spear', castle: 'Castle' },
    pairData: {
      'motion|none': { base: 'Arcane Bolt', desc: 'Pushes your crest\'s mana out as it is. Cheap and fast, no side effects.', tags: ['Pure release', 'Efficient', 'Rapid'] },
      'bind|none': { base: 'Solidify', desc: 'Compresses mana into a dense barrier. With a held thread, recall (G) returns some mana.', tags: ['Solidify', 'Barrier', 'Recallable'] },
      'divide|none': { base: 'Unravel', desc: 'Unties foreign structures: strips wards and counterforce, and breaks spell-made walls.', tags: ['Strip', 'Break', 'Anti-ward'] },
      'convert|none': { base: 'Drain', desc: 'Rewrites the crest of the mana it touches and steals it as your own.', tags: ['Steal', 'Sustain', 'Low power'] },
      'grow|none': { base: 'Mend', desc: 'Refills broken structure with your crest\'s mana.', tags: ['Heal', 'Support', 'Conversion loss'] },
      'phase|none': { base: 'Phase Shift', desc: 'Shifts your phase for an instant, slipping through the next attack.', tags: ['Evasion', 'I-frames', 'Low power'] },
      'bind|motion': { base: 'Inertia Tether', desc: 'Binds the force of movement and keeps pulling the target back.', tags: ['Bind', 'Pull', 'Anchor'] },
      'divide|grow': { base: 'Corrosive Spores', desc: 'Decay multiplies itself into a toxic field that eats what it touches.', tags: ['Poison', 'Erosion', 'Spread'] },
      'bind|grow': { base: 'Rootbind', desc: 'Binding grows into the ground and pins the target in place.', tags: ['Root', 'Root wall', 'Terrain'] },
      'motion|motion': { base: 'Resonant Shock', desc: 'Synchronizes two motions and releases a circular shock from the point of impact.', tags: ['Shockwave', 'Knockback', 'Shatter'] },
      'convert|grow': { base: 'Bio-Transcription', desc: 'Turns stolen essence into a growing structure that settles as a healing field.', tags: ['Absorb', 'Regrowth', 'Field'] },
      'bind|phase': { base: 'Phase Prison', desc: 'Binds the target\'s phase to space and seals movement across the boundary.', tags: ['Isolate', 'Seal', 'Defense'] },
      'divide|phase': { base: 'Void Erosion', desc: 'Dissolves only phase boundaries, slipping past barriers.', tags: ['Pierce', 'Ignore wards', 'Heavy'] },
      'motion|phase': { base: 'Blink Pierce', desc: 'Sends your phase ahead to where the motion lands, leaping spell and caster there.', tags: ['Teleport', 'Pierce', 'Ambush'] },
      'convert|divide': { base: 'Collapse Conversion', desc: 'Converts broken structure into unstable essence and collapses the ground itself.', tags: ['Corrode', 'Terrain break', 'Harvest'] },
      'convert|motion': { base: 'Counterforce', desc: 'Converts incoming motion into essence and fires it back.', tags: ['Reflect', 'Absorb', 'Counter'] },
      'grow|motion': { base: 'Chain Wave', desc: 'Each time motion spreads it grows the next wave, chaining across targets.', tags: ['Chain', 'Ripple', 'Area control'] },
      'bind|convert': { base: 'Matter Wall', desc: 'Rebinds the surrounding ground into a barrier of changed nature.', tags: ['Barrier', 'Terrain', 'Transmute'] },
      'divide|motion': { base: 'Rending Blade', desc: 'Dissolves the path of motion itself, cutting everything along the line.', tags: ['Cut', 'Line', 'Armor pierce'] },
      'grow|phase': { base: 'Mirror Veil', desc: 'Multiplies your phase into several images that divert attacks.', tags: ['Clones', 'Evasion', 'Confusion'] },
      'bind|bind': { base: 'Bulwark Ward', desc: 'Closes binding twice over into a damping ward that surrounds you.', tags: ['Defense', 'Support', 'Damping'] },
      'convert|phase': { base: 'Phase Inversion', desc: 'Rewrites the phase of incoming spells and returns them to you as essence.', tags: ['Harvest', 'Nullify', 'Rebuild'] },
      'grow|grow': { base: 'Swarm Bed', desc: 'Growth breeds growth; self-propelled shards chase the target.', tags: ['Homing', 'Numbers', 'Sustain'] },
      'phase|phase': { base: 'Coherent Scan', desc: 'Overlaps phases to read the structure (health, essence) of whatever it touches.', tags: ['Scan', 'Intel', 'Low power'] },
      'convert|convert': { base: 'Essence Well', desc: 'Layers conversion into a well that draws surrounding essence to one point.', tags: ['Gather', 'Recovery', 'Placed'] },
      'bind|divide': { base: 'Trench', desc: 'Splits the ground into a trench you can hide in. Blocks lines of fire.', tags: ['Cover', 'Terrain', 'Defense'] },
      'divide|divide': { base: 'Unmaking Field', desc: 'Unties every binding. Terrain and spells alike come undone.', tags: ['Dispel', 'Terrain break', 'Heavy'] }
    },
    presets: {
      bolt: { label: 'Pure release (1 part)' }, shock: { label: 'Resonant Shock Needle' }, guided: { label: 'Thread-guided' }, beam: { label: 'Piercing Ray' },
      remote: { label: 'Remote detonation' }, solid: { label: 'Solid shield (recallable)' }, wall: { label: 'Matter Wall' }, barrier: { label: 'Mana barrier' },
      blades: { label: 'Orbiting blades (solid)' }, spear: { label: 'Crystal spear (solid)' }, shuriken: { label: 'Shuriken (solid)' }, katana: { label: 'Light katana' },
      axe: { label: 'Siege axe (solid)' }, chakram: { label: 'Chakram (solid)' }, arrow: { label: 'Light arrows (×3)' }, bastion: { label: 'Stone wall (solid)' },
      castle: { label: 'Castle (orbiting walls)' }, aegis: { label: 'Perfect Ward' }, reflect: { label: 'Reflect' }, shift: { label: 'Nullify' }, poison: { label: 'Corrosion trap' },
      blink: { label: 'Blink Pierce' }, well: { label: 'Essence Well' }, mend: { label: 'Self-mend' }, haste: { label: 'Haste (enhance)' }, harden: { label: 'Harden (enhance)' },
      vital: { label: 'Vitality (enhance)' }, heavy: { label: '9-part heavy spell' }
    },
    schools: [
      { name: 'Radiant Archer', spells: [{ customName: 'Meteor' }, { customName: 'Heavenpiercer' }, { customName: 'Bastion' }, { customName: 'Gale' }] },
      { name: 'Sword Saint', spells: [{ customName: 'Moonhaze Cut' }, { customName: 'Double Sakura' }, { customName: 'Shrinking Step' }, { customName: 'Dusk Reaper' }] },
      { name: 'Lord of the Keep', spells: [{ customName: 'Siegebreaker' }, { customName: 'Golden Keep' }, { customName: 'Absolute Wall' }, { customName: 'Earthquake' }] },
      { name: 'Hexweaver', spells: [{ customName: 'Miasma Seed' }, { customName: 'Binding Chains' }, { customName: 'Soul Eater' }, { customName: 'Hollow Lance' }] },
      { name: 'Demolitionist', spells: [{ customName: 'Blast Seal' }, { customName: 'Skyfall' }, { customName: 'Scattered Bloom' }, { customName: 'Reversal' }] },
      { name: 'Swarm Caller', spells: [{ customName: 'Thousand Petals' }, { customName: 'Trident Thunder' }, { customName: 'Soul Siphon' }, { customName: 'Regrowth' }] },
      { name: 'Thunder Emperor', spells: [{ customName: 'Thunder Spear' }, { customName: 'Heaven\'s Lightning' }, { customName: 'Thunder Ring' }, { customName: 'Essence Well' }] },
      { name: 'Mirror Witch', spells: [{ customName: 'Moon Ring' }, { customName: 'Mirror Blossom' }, { customName: 'Water Mirror' }, { customName: 'Chain of Inertia' }] }
    ],
    rooms: { ichi: { name: 'First Hall', note: 'Standard size. Good for your first battle' }, sema: { name: 'The Narrows', note: 'Tight; fights break out fast' }, oo: { name: 'Great Hall', note: 'Wide. Survive until you grow big' }, dojo: { name: 'Training Hall', note: 'Test your spells on dummies. Nothing is recorded' } },
    dummies: [{ name: 'Dummy: Still' }, { name: 'Dummy: Walker' }, { name: 'Dummy: Wall' }, { name: 'Dummy: Shooter' }, { name: 'Dummy: Cannon' }],
    tiers: [{ name: 'Crestless' }, { name: 'First Crest' }, { name: 'Second Crest' }, { name: 'Third Crest' }, { name: 'Fourth Crest' }, { name: 'Fifth Crest' }, { name: 'Crestsmith' }, { name: 'Crest Saint' }],
    inks: { pink: { name: 'Rose' }, blue: { name: 'Azure' }, yellow: { name: 'Gold' }, green: { name: 'Leaf' }, orange: { name: 'Flame' }, purple: { name: 'Violet' }, teal: { name: 'Jade' }, red: { name: 'Crimson' } },
    crests: { ring: 'Ring', bar: 'Barred ring', cross: 'Cross', lozenge: 'Lozenge', igeta: 'Well frame', scale: 'Scales', stars: 'Three stars', wheel: 'Linked rings' },
    botNames: ['Vesper', 'Ashen', 'Noctis', 'Morrow', 'Grave', 'Umbra', 'Sable', 'Wraith', 'Cinder', 'Hollow', 'Rook', 'Crow', 'Ember', 'Lament', 'Requiem', 'Vigil', 'Shroud', 'Obsidian', 'Thorn', 'Omen',
      'Dusk', 'Gloam', 'Ravel', 'Hex', 'Mourn', 'Solace', 'Blight', 'Styx', 'Kestrel', 'Nadir', 'Onyx', 'Pyre', 'Quill', 'Rune', 'Sorrow', 'Tallow', 'Umber', 'Vane', 'Wither', 'Zephyr'],
    cries: {
      win: ['Victory is not proof. It is the start of the next question.', 'What this crest records is not the victor\'s name, but a choice.', 'For now, I shaped scattering power into protection.', 'I won. Still, what I broke will not return.',
        'I did not read everything. I only overcame one doubt.', 'Strength is knowing what you need not break.', 'The hand that ties the thread and the hand that cuts it were the same.', 'I will carry even the silence after victory.',
        'Not a difference in vessels. I simply kept choosing until the end.', 'This win will not be the end.', 'Know the weight of a different crest.', 'It\'s over.', 'Too slow.', 'Scatter.', 'Return to ash.'],
      death: ['…My crest unravels. I was myself to the end.', 'The vessel breaks, but the path I chose remains…', 'Even scattering mana has a place to return…', 'I will not forget what I failed to protect…',
        'This defeat, too, becomes part of the next structure…', 'The thread is cut. I can entrust it to no one now…', 'Winning was never the only right answer…', 'Life scatters. Still, the wish remains…',
        'It wasn\'t the spell that erred. It was my fear…', 'To the last fragment, my will is mine…', 'Gh… aaagh!', '…So this is where it ends.', 'Ngh… the dark takes me…', 'Impossible… not me…', 'Such regret…']
    },
    defaultCries: { win: 'Behold — the power of the crest!', death: 'Ngh… I can\'t scatter yet…!' },
    howto: [['Move', 'WASD / arrow keys'], ['Switch spells', '1·2·3·4 / wheel / click a slot'], ['Cast', 'Aim with the mouse, left click (hold to keep chanting)'], ['Dodge', 'Right click / Space'],
      ['Detonate', 'F (signals spells with the Command trigger)'], ['Recall', 'G (unravels held-thread spells, returning some mana)'], ['Spell forge', 'T (in the training hall, lobby, or after falling)'],
      ['Sound', 'M sound effects, N music, V voice (none / names / names & cries), B change track. More in Settings']],
    rules: [
      'Build spells in the spell forge. Choose what happens (principles), its shape, how it travels, when it fires and what follows, and it becomes one of 27 phenomena.',
      'More parts mean more cost, longer chants and less power. Simple spells with few parts are the most efficient and hit hardest. The number of parts you can handle (control capacity) grows with level: 4 at LV0, 5 at LV3, 7 at LV7, 9 at LV12. Beyond it, a spell may misfire as you cast.',
      'Spells are released as Solid or Energy. Energy pierces solid wards; solid strips energy wards; like stops like. Orbit a solid spell and blades circle you, both shield and weapon.',
      'Released spells weaken the farther they travel. Rays and spears barely fade. Shapes (needle, arrow, sword, katana, scythe, axe, hammer, shuriken, chakram, spear, castle…) change speed, hitbox and ward-piercing power.',
      'A Perfect ward layers solid and energy and stops everything. But it is very costly: mana drains while it stands, you move slowly, and casting dissolves it.',
      'Spells of different crests collide in midair. Solid on solid: the weaker shatters. Energy on energy: they cancel. Energy piercing solid is greatly weakened and erodes the solid. A burst\'s blast snuffs foreign energy shots and knocks solid ones away. Rays burn away foreign energy shots.',
      'Your own spells never repel each other; they combine. Energy shots Fuse into one, energy touching your solid shot Imbues it, shots and rays passing your energy fields Resonate, and bursts Chain-blast your nearby traps. Your wards let your spells through, so you can fire over your own walls. Catching your chakram returns half its mana.',
      'The six crests on the floor are the Nodes of the six principles. Stand in a ring to empower spells with that principle, lower their cost, and let mana well up. Standing in the central Keystone Circle raises control capacity by 1.',
      'Test your spells on dummies in the training hall. Press T there to rebuild at any time.',
      'On the battlefield, collect the glowing motes (essence) to grow and restore mana. Mana does not refill by itself (it wells up only inside the nodes). Essence is your score. Scattered foes spill their essence, and you take some of their mana.',
      'When you fall, the run ends. Your score and place become rank points. Jump right back in.'
    ],
    chant: {
      a: { motion: 'Run swift', bind: 'Bind and harden', divide: 'Come undone', convert: 'Shift and return', grow: 'Sprout and fill', phase: 'Phase, waver' },
      b: { motion: 'tearing the wind', bind: 'layering bonds', divide: 'splitting reason', convert: 'rewriting the crest', grow: 'carrying life', phase: 'crossing shadows', none: '' },
      behavior: { project: '', homing: 'let none escape', lob: 'rain down', sow: 'become a seed', drop: 'be here', orbit: 'circle me', relay: 'strike three ways', beam: 'pierce' },
      form: { point: '', line: '', plane: 'become a wall', ring: 'become a ring', field: 'fill the field' },
      deploy: { single: '', burst: 'burst', scatter: 'scatter', linger: 'remain', sprinkle: 'sprinkle', siphon: 'devour' }
    }
  }
};

// ═══ 中文（简体） ══════════════════════════════════════════════
LANG.zh = {
  ui: {
    '・': '·', '！': '！', '／': '／', '{0}{1}。': '{0}{1}。',
    '加速': '加速', '硬化': '硬化', '活性': '活性', '自分の紋の魔力を体へ書き込んだ': '将自身纹章的魔力写入了身体',
    '暴发': '暴发', '暴発': '暴发', '「{0}」は制御容量を超えていた': '「{0}」超出了控制容量', '術式が…崩れる！': '术式……要崩溃了！',
    '結界崩壊': '结界崩坏', '貫通': '贯通', '剥離': '剥离', '「{0}」の節点': '「{0}」之节点',
    '{0}を含む術が強まり（威力 ×{1}・消費 ×{2}）、輪の中では魔力が湧き出る': '含{0}的术得到强化（威力 ×{1}·消耗 ×{2}），圈内魔力会涌出',
    '要の陣': '要之阵', 'ここに立つ間は制御容量が +{0}。重い術を暴発させずに扱える': '站在此处时控制容量 +{0}。可稳定施放重型术',
    '共鳴': '共鸣', '相殺': '抵消', '融合': '融合', '魔装': '魔装', '誘爆': '诱爆',
    '完全結界が解けた': '完全结界解除了', '魔力が尽きた': '魔力耗尽', '術を唱えると解ける': '咏唱术时会解除',
    '+{0} 魔力': '+{0} 魔力', '糸が切れた': '丝线断了', '術者から離れすぎた': '离施术者太远', '糸を断たれた': '丝线被切断',
    '回収 +{0} 魔力': '回收 +{0} 魔力', '糸でつながった術式 {0} つをほどいた': '解开了 {0} 个丝线相连的术式', '構造崩壊': '结构崩坏',
    '{0} を散らした': '击散了 {0}', '+{0} 魔素': '+{0} 魔素',
    '制御容量が {0} になった。より重い術を安定して放てる': '控制容量提升至 {0}。可以稳定施放更重的术', '次の制御容量まで育て': '继续成长以获得下一级控制容量',
    '曲を変えた': '已切换曲目', '声なし': '无语音', '技名だけ': '仅技名', '技名と叫び': '技名与呐喊', '声：{0}': '语音：{0}',
    '要の陣 ― 制御容量 +{0}': '要之阵 ― 控制容量 +{0}', '{0}の節点 ― {0}の術が強まり、魔力が湧く': '{0}之节点 ― {0}之术强化，魔力涌出',
    '{0}人': '{0}人', 'LV {0}・制御容量 {1}': 'LV {0}·控制容量 {1}', '（LV{0}で{1}）': '（LV{0} 时为 {1}）',
    '魔力 {0}': '魔力 {0}', '部品 {0}/{1}': '部件 {0}/{1}', '・暴発 {0}%': '·暴发 {0}%', '糸 {0}': '丝线 {0}', 'F 指示起爆（{0}）': 'F 指令起爆（{0}）', 'G 回収': 'G 回收',
    '与えた威力 {0}・毎秒 {1}': '造成伤害 {0}·每秒 {1}', '受けた威力 {0}・防いだ {1}': '承受伤害 {0}·抵挡 {1}', '攻撃人形：撃つ': '攻击人偶：开火', '攻撃人形：止める': '攻击人偶：停止',
    '{0} に散らされた': '被 {0} 击散', '結界の外で散った': '在结界外消散', '{0} が結界に散った': '{0} 消散了',
    '攻撃人形が撃ちはじめた': '攻击人偶开始射击', '攻撃人形を止めた': '已停止攻击人偶', '受けた威力と、結界で防いだ数を数える（修練場では散らない）': '统计承受的伤害与结界挡下的次数（修炼场中不会消散）',
    '技': '技', '声': '声', '声：{0}（V で切り替え）': '语音：{0}（按 V 切换）', '自動（ブラウザに合わせる）': '自动（跟随浏览器）', '　◆自然': '　◆自然', '（日本語の声が見つからない）': '（未找到该语言的语音）',
    '首位　{0}　{1}': '首位　{0}　{1}', '次の「{0}」まで {1} pt': '距「{0}」还差 {1} pt', '最上位の位階': '最高位阶', '{0}位': '第{0}名', '撃破 {0}': '击破 {0}',
    '<li class="empty">まだ入場していない</li>': '<li class="empty">尚未参战</li>', '部品 {0}・魔力 {1}': '部件 {0}·魔力 {1}', '原理負荷 {0}': '原理负荷 {0}', 'なし': '无',
    '単一原理（純放出）。最も軽く速い': '单一原理（纯放出）。最轻最快', '負荷 {0}・半径 {1}': '负荷 {0}·半径 {1}', '自動': '自动', '広がり方から決める（弾は針、細い波は結晶、ほかは球）': '由扩散方式决定（小弹为针、细波为晶、其余为球）',
    '{0}（速さ×{1}・当たり×{2}・威力×{3}・結界へ×{4}{5}）': '{0}（速度×{1}·判定×{2}·威力×{3}·对结界×{4}{5}）', '・形作る負荷 {0}': '·塑形负荷 {0}',
    '作例「{0}」を {1} に読み込んだ': '已将范例「{0}」载入第 {1} 格', '流派「{0}」の4つの術を読み込んだ（{1}）': '已载入流派「{0}」的四个术（{1}）', '{0}の「{1}」を {2} に読み込んだ': '已将{0}的「{1}」载入第 {2} 格', '初期の4つに戻した': '已恢复初始四个术',
    'まっすぐ飛ばす': '笔直射出', '放ち、違う紋の大きな魔力へ曲がらせる': '放出后弯向异纹的大魔力', '放物線で狙った地点へ落とす': '以抛物线落向目标点', '足元近くへ転がして止める': '滚到脚边附近停下',
    '自分の足元に置く': '放在自己脚下', '自分の周りに纏う': '缠绕在自身周围', '三方へ撃ち分ける': '向三个方向分射', '一直線の光にして貫く': '化作一线之光贯穿',
    '触れた瞬間に': '接触瞬间', '殻が割れる時（時限）に': '外壳破裂时（定时）', '違う紋が近づいた時に': '异纹接近时', 'F の合図で': '收到 F 信号时',
    '一度作用する': '作用一次', '大きく炸裂する': '大范围炸裂', '追尾する小片に分かれる': '分裂为追踪碎片', 'その場に領域として残る': '作为领域留在原地', '攻撃せずに魔力の粒と囮を撒く': '不攻击，撒出魔力粒与诱饵', '領域の中の敵から魔力と魔素を奪い続ける': '持续夺取领域内敌人的魔力与魔素',
    '強化術：自分の紋の魔力を体へ書き込み、{0}。': '强化术：将自身纹章的魔力写入身体，{0}。', '動きを速くする（加速）': '使动作变快（加速）', '受ける威力を減らす（硬化）': '减少所受伤害（硬化）', '体力を少しずつ戻す（活性）': '逐渐恢复体力（活性）',
    '完全：固体とエネルギーを重ね、どちらの質も光線も通さない。引き換えに、張っている間は魔力が戻らず毎秒減り、足が重く、術を唱えると解ける。': '完全：叠合固体与能量，任何质与光线都无法通过。代价是展开期间魔力不回复且每秒减少、行动迟缓，咏唱术时即解除。',
    '{0}枚の城壁で自分をぐるりと囲む（ほとんど回らない）。弾を受け止める壁になる': '以 {0} 面城墙环绕自身（几乎不转动），成为挡下弹体的墙',
    '{0}本の{1}を自分の周りに回らせる。弾を受け止め、触れた相手を斬る': '让 {0} 把{1}绕身旋转，挡下弹体并斩击触碰的对手', '刃': '刃',
    '「{0}」を固体にして、{1}。': '将「{0}」固体化，{1}。', 'エネルギーの弾は貫いてくる。エネルギーの結界は剥がせる。': '能量弹会贯穿而来。可剥离能量结界。', '糸でつながり、回収（G）できる。': '以丝线相连，可回收（G）。',
    '「{0}」を{1}。': '将「{0}」{1}。', '{0}の「{1}」を{2}{3}。': '将{0}的「{1}」{2}{3}。', '固体（結晶）にして': '固化为结晶后', 'エネルギーのまま': '保持能量',
    '周りに入った違う紋に{0}。': '对进入周围的异纹{0}。', '作用し続ける': '持续作用',
    '固体の結界には止められるが、エネルギーの結界は剥がせる。': '会被固体结界挡住，但能剥离能量结界。', '固体の結界は貫けるが、エネルギーの結界には止められる。': '能贯穿固体结界，但会被能量结界挡住。',
    '六枚の面の壁で囲む城壁になる。': '成为以六面墙围起的城墙。', '一枚の面の壁になる。': '成为一整面墙。', '形：{0}。': '形状：{0}。',
    '放った後も糸でつながり、誘導・指示起爆（F）・回収（G）ができる（維持費がかかる）。': '放出后仍以丝线相连，可诱导、指令起爆（F）、回收（G）（需维持消耗）。', '追加性質：{0}。': '追加性质：{0}。',
    '貫通光線は「細い波・接触・単発・糸：切断」で固定': '贯通光线固定为「细波·接触·单发·丝线：切断」', '貫通光線は光そのもの。質は「エネルギー」だけ': '贯通光线本身就是光，质只能是「能量」',
    '完全は結界を作る術（固化・物性編壁・掘削塹壕・根絡・位相牢・重縛結界・位相転換・反力変換）と周回にだけ使える': '完全只能用于构筑结界的术（固化·物性编壁·掘削堑壕·根缚·相位牢·重缚结界·相位转换·反力转换）与环绕',
    '周回は常に起動しているので「接触」だけ': '环绕始终处于启动状态，只能「接触」', '周回の追加機能は「単発・残留・吸魔」だけ': '环绕的追加功能只有「单发·残留·吸魔」', '指示起爆は糸を通して合図を送るので「維持」が必要': '指令起爆需通过丝线传递信号，必须「维持」',
    '部品 {0}': '部件 {0}', '{0}（押すと外す）': '{0}（点击移除）', 'なし（最大{0}つ・重複可）': '无（最多 {0} 个·可重复）', '現象：{0}': '现象：{0}', '{0}秒': '{0}秒', '純度 ×{0}（部品が少ないほど重い）': '纯度 ×{0}（部件越少越强）',
    'LV{0}〜 容量{1}': 'LV{0}起 容量{1}', '・安定': '·稳定', '決定して試す': '确定并试用', '修練場で試す': '在修炼场试用', '糸{0}': '丝线{0}', '名無し': '无名氏',
    '人形を相手に術を試す。T で術式台、Esc で戻る': '以人偶试术。T 打开术式台，Esc 返回', '術を放つと入場保護が解ける': '施术后入场保护解除', '左をなぞって歩く': '滑动左侧移动', '右をタッチして放つ': '点击右侧施术', '下の枠で持ち替え': '用下方栏位切换',
    '左クリック': '左键', '放つ': '施放', '持ち替え': '切换', '回避': '闪避', '退出': '退出', '歩く': '移动', '魔導士を動かしてみよう。': '试着移动魔导士。', '矢印キー': '方向键', '画面の左半分をなぞる': '滑动屏幕左半边', '術を放つ': '施放术',
    'マウスで狙い、左クリックで術を放つ。押し続けると続けて唱える。放つたびに魔力（青い帯）を使う。戦場では魔力は勝手に戻らず、光の粒（魔素）を拾うと戻る。': '用鼠标瞄准，左键施术。按住可连续咏唱。每次施术消耗魔力（蓝条）。战场上魔力不会自动回复，拾取光粒（魔素）即可回复。',
    'マウスで狙う': '鼠标瞄准', '画面の右半分をタッチ': '点击屏幕右半边', '人形に当てる': '命中人偶', '近くの人形に術を当てよう。当てた威力は上の「与えた威力」に出る。': '用术命中附近的人偶。伤害显示在上方的「造成伤害」。', '人形の方をタッチ': '朝人偶方向点击',
    '術を持ち替える': '切换术', '術は4つまで持てる。2〜4に持ち替えて放ってみよう。4の「物性編壁」は相手の術を止める壁になる。': '最多携带四个术。切换到 2〜4 试着施放。4 号「物性编壁」会成为挡住对方术的墙。', 'ホイール': '滚轮', '下の枠をクリック': '点击下方栏位', '下の枠をタッチ': '点击下方栏位',
    '一瞬だけ素早く跳んで、飛んでくる術をかわす（魔力を少し使う）。': '瞬间疾跃，躲开飞来的术（消耗少量魔力）。', '右クリック': '右键', '回避ボタン': '闪避按钮', '術を組む': '构筑术',
    '術式台で原理と部品をつないで、自分の術を作る。名前を付けると、放つときにその技名を叫ぶ。開いて「決定」で閉じよう。': '在术式台连接原理与部件，创造自己的术。命名后施放时会喊出技名。打开后按「确定」关闭。', 'T で術式台': 'T 打开术式台', '決定 / Esc': '确定 / Esc', '上の「術式台」ボタン': '上方的「术式台」按钮', '準備はできた': '准备完毕',
    '戦場では地面の魔素を拾うと育ち、相手を散らすとその魔素を奪える。育つほど制御容量が増え、重い術も暴発させずに扱える。装いも格が上がる。魔力は光の粒を拾うと戻る。散ったらすぐ入りなおせる。': '在战场上拾取地面的魔素即可成长，击散对手可夺取其魔素。越成长控制容量越高，重型术也不会暴发。装束也会随之升格。拾取光粒可回复魔力。消散后可立即重新进入。',
    '修練場に残る': '留在修炼场', '手ほどきを終える': '结束教学', '結界の外で構造が崩れた': '在结界外结构崩坏', '{0}・計 {1} pt': '{0}·共 {1} pt', '表示で問題が起きた': '画面出现问题', 'このまま遊べるが、続くときは再読み込みしてほしい': '可以继续游玩，若持续出现请重新载入',
    '光のにじみを切った': '已关闭光晕', '動きが重かったため。設定で戻せる': '因运行较卡。可在设置中恢复', 'PRIMA 紋戦': 'PRIMA 纹战', 'このゲームは JavaScript で動きます。ブラウザの設定で JavaScript を有効にしてください。': '本游戏需要 JavaScript。请在浏览器设置中启用。',
    '魔素': '魔素', '撃破': '击破', '一の間': '一之间', '手ほどき': '教学', '戦場へ入る': '进入战场', '構造': '结构', '魔力': '魔力', '避': '避', '修練場': '修炼场', '与えた威力 0': '造成伤害 0', '受けた威力 0・防いだ 0': '承受伤害 0·抵挡 0', '術式台': '术式台', 'ロビーへ': '大厅',
    '音': '音', '曲': '曲', '設': '设', '紋戦': '纹战', '原理を接続して術を組み、乱戦で放て。': '连接原理构筑术式，在乱战中释放。', 'はじめての方へ': '新手指引', '修練場で、動き方・術の放ち方・術の組み方を実際にやってみる（3分ほど）。': '在修炼场实际体验移动、施术与构筑术式（约3分钟）。',
    '手ほどきを始める': '开始教学', '名前': '名字', '光の色': '光的颜色', '紋': '纹章', '丸': '圆', 'ルーム': '房间', '戦場の参加者はいまはBotです。オンライン対戦は準備中。': '目前战场上的对手都是 Bot。联网对战筹备中。', '遊び方': '玩法', '設定（声・音・画面）': '设置（语音·声音·画面）',
    '術': '术', '術式台を開く': '打开术式台', '勝利宣言': '胜利宣言', '倒したときに叫ぶ': '击倒对手时喊出', '断末魔': '临终之言', '散ったときに叫ぶ': '消散时喊出', '声で試す': '试听语音', '無': '無', '無紋': '无纹',
    '次の位階まで 250 pt': '距下一位阶 250 pt', '最高魔素': '最高魔素', '最高順位': '最高名次', '通算撃破': '累计击破', '入場': '参战', '最近の入場': '最近参战', '散った': '已消散', '生存': '存活', '位階が上がった': '位阶提升', 'もう一度入る': '再次进入', '術式を組み直す': '重新构筑术式',
    '原理と部品を接続して、1〜4 の枠に術を組む。部品が増えるほど消費と詠唱が重くなり、制御容量を超えると暴発しうる。': '连接原理与部件，在 1〜4 栏构筑术。部件越多消耗与咏唱越重，超过控制容量可能暴发。',
    '決定': '确定', '何が起こる': '发生什么', '主原理': '主原理', 'もう一つの性質': '另一种性质', '副原理': '副原理', '形': '形', '広がり方': '扩散方式', 'どう届く': '如何送达', '届き方': '送达方式', 'いつ起こる': '何时触发', '発動': '发动', '起きた後': '触发之后', '追加機能': '追加功能',
    '放った後': '放出之后', '糸': '丝线', '上乗せ': '叠加', '追加性質': '追加性质', '強': '强', '強弱': '强弱', '威力': '威力', '時限・持続': '定时·持续', '連射': '连射', '質': '质', '固めるか': '是否凝固', '固体／エネルギー': '固体／能量', '刃の形': '刃之形', '速さ・当たり・衰え': '速度·判定·衰减',
    '空欄なら現象の名前。付けると放つときに唱える': '留空则使用现象名。命名后施放时会喊出', '魔弾針': '魔弹针', '部品': '部件', '詠唱': '咏唱', '遠くで': '远处', '制御容量と暴発': '控制容量与暴发', '部品にふれると、その意味がここに出る': '指向部件即可在此看到说明',
    '達人の流派': '达人流派', 'Bot が修める4つの術を丸ごと読み込む': '整套载入 Bot 所修的四个术', '達人の術': '达人之术', '作例': '范例', '初期の4つに戻す': '恢复初始四个', '六原理（単一原理で放つと）': '六原理（单一原理施放时）', '閉じる': '关闭', '設定': '设置', '言語': '语言',
    '名前を付けた術を放つとき、その技名を叫ぶ。「技名と叫び」は勝利宣言と断末魔も声に出す。': '施放已命名的术时喊出技名。「技名与呐喊」也会念出胜利宣言与临终之言。', '声の種類': '语音种类', '試す': '试听', '「Natural」「Online」と付いた声がいちばん人に近い（Edge・Chrome で使える）。': '带「Natural」「Online」的语音最接近真人（Edge·Chrome 可用）。',
    '効果音': '音效', '音楽': '音乐', '曲を変える': '切换曲目', '光のにじみ': '光晕', '術の光がまわりへにじむ。重いときは切る': '术的光向四周晕开。卡顿时请关闭',
    '原理を接続して自分の術を組み、ルームの乱戦で放つ。魔素を拾い、散らして奪い、散ったらすぐ入りなおす魔法の乱戦。': '连接原理构筑自己的术，在房间乱战中释放。拾取魔素、击散夺取、消散后立即重返的魔法乱战。', 'PRIMA 紋戦 — 術を組み、乱戦で放て': 'PRIMA 纹战 — 构筑术式，于乱战中释放',
    '原理をつないで自分だけの魔法を組み、魔導士の乱戦で放つブラウザゲーム。登録不要・すぐ遊べる。': '连接原理构筑专属魔法，在魔导士乱战中释放的浏览器游戏。免注册，即开即玩。', '戦場': '战场', '自分の状態': '自身状态', '順位': '排名', '体と刻印': '身体', '回避（右クリック / Space）': '闪避（右键 / Space）',
    '射（槍・魔弾・日本刀・手裏剣）と砲（光線・斧）の人形が撃ってくる': '射手人偶（枪·魔弹·日本刀·手里剑）与炮手人偶（光线·斧）会攻击你', '全体図': '全图', '効果音（M）': '音效（M）', '音楽（N）': '音乐（N）', '声（V）': '语音（V）', 'ロビーへ戻る（Esc）': '返回大厅（Esc）', '術と叫び': '术与呐喊', '位階': '位阶', '術の枠': '术栏', '術の動きの見本': '术的动作示范', '（自動）': '（自动）'
  },
  data: {
    naming: { join: '', extraSep: '·', beam: '{0}贯通光线', beamStrip: '刃', shapeSuffix: { needle: '针', orb: '弹', shard: '刃', arrow: '矢', blade: '剑', katana: '太刀', scythe: '镰', axe: '斧', hammer: '锤', shuriken: '星', chakram: '轮', spear: '枪', castle: '城' } },
    principles: { motion: { name: '运动' }, bind: { name: '结合' }, divide: { name: '分解' }, convert: { name: '转换' }, grow: { name: '增殖' }, phase: { name: '相位' } },
    noPrinciple: { name: '无' },
    forms: { point: { name: '小弹', suffix: '针' }, line: { name: '细波', suffix: '脉' }, plane: { name: '墙', suffix: '壁' }, ring: { name: '周围', suffix: '环' }, field: { name: '广域', suffix: '域' } },
    behaviors: {
      project: { name: '射出', note: '直线飞行。会被岩石与结界阻挡。越远威力越弱' }, homing: { name: '追踪', note: '弯向异纹的大魔力。维持丝线可引导至准星' },
      lob: { name: '投射', note: '以抛物线越过结界与岩石。落点有预告' }, sow: { name: '播种', note: '在脚边附近撒下种子。滚动后停下成为陷阱' },
      drop: { name: '原地', note: '设置在当前位置' }, orbit: { name: '环绕', note: '跟随施术者，始终启动。单一原理为强化术。固体化则刃环绕周身' },
      relay: { name: '扇射', note: '向三个方向分射。容易消散' }, beam: { name: '贯通光线', note: '贯穿敌人的高输出光线，远处也几乎不衰减。贯穿固体结界，足够强时可击碎能量结界' }
    },
    triggers: { contact: { name: '接触', note: '命中或接触时启动' }, fuse: { name: '定时', note: '外壳消散破裂时启动（射出会在瞄准点炸裂）' }, proximity: { name: '感知', note: '异纹进入范围时启动。停下的术式会成为陷阱' }, command: { name: '指令', note: '通过丝线的信号启动（F）。丝线自动维持' } },
    deploys: { single: { name: '单发', note: '按扩散方式作用一次' }, burst: { name: '炸裂', note: '扩大范围，瞬间炸裂' }, scatter: { name: '分裂', note: '分裂为追踪碎片' }, linger: { name: '残留', note: '领域长时间残留' }, sprinkle: { name: '散魔', note: '不攻击，将消耗化为魔力粒撒出。谁都能拾取，也可作为追踪的诱饵' }, siphon: { name: '吸魔', note: '夺取领域内敌人的魔力与魔素，并将周围魔素吸向施术者。威力减半' } },
    links: { cut: { name: '切断', note: '放出瞬间切断丝线。无维持消耗。只按术式行动' }, hold: { name: '维持', note: '持续以丝线相连。需维持消耗，但可引导、指令起爆（F）、延寿、回收（G）' } },
    extraEffects: { motion: { note: '命中时追加击飞' }, bind: { note: '命中时减速。叠两层会短暂束缚' }, divide: { note: '剥除结界与外壳，威力 +8%' }, convert: { note: '命中时夺取对方魔力' }, grow: { note: '命中时生成追踪碎片' }, phase: { note: '不易受结界与硬化的减伤影响' } },
    matters: { energy: { name: '能量', note: '以光与热的形态放出。快但远处易消散。可贯穿固体结界，会被能量结界挡住' }, solid: { name: '固体', note: '凝固为结晶放出。慢但沉重，不易衰减。可剥离能量结界，会被固体结界挡住。固体结界非常坚固' }, perfect: { name: '完全', note: '叠合固体与能量的完全结界，什么都无法通过。但消耗极大，展开期间魔力持续减少、行动迟缓，咏唱术时解除（仅限结界与环绕）' } },
    shapes: {
      needle: { name: '针', note: '细而快。判定小' }, orb: { name: '球', note: '大而易中，稍慢' }, shard: { name: '结晶', note: '尖锐的结晶。对结界稍强' }, arrow: { name: '矢', note: '最细最快的矢。判定极小，射程远' },
      blade: { name: '剑', note: '宽刃直剑。判定大、打击重，远处变钝' }, katana: { name: '日本刀', note: '弯刃。斩穿一人，也能砍到后方对手' }, scythe: { name: '大镰', note: '弧形巨刃。判定最广，可横扫三人，射程短' },
      axe: { name: '斧', note: '沉重的斧。慢但一击重，能劈开结界' }, hammer: { name: '锤', note: '巨锤。对结界最强，将对手大幅击飞' }, shuriken: { name: '手里剑', note: '旋转的四刃星。碰到岩石或结界可反弹两次' },
      chakram: { name: '圆月轮', note: '旋转之轮。飞远后会回到手中，回程也能命中' }, spear: { name: '枪', note: '长枪尖。最不衰减，贯穿结界之力强' }, castle: { name: '城', note: '石砌城墙。射出为缓慢沉重的石块；环绕则城墙围住自身，几乎不转' }
    },
    visualShapes: { auto: '自动', needle: '针', orb: '球', shard: '结晶', arrow: '矢', blade: '剑', katana: '日本刀', scythe: '大镰', axe: '斧', hammer: '锤', shuriken: '手里剑', chakram: '圆月轮', spear: '枪', castle: '城' },
    pairData: {
      'motion|none': { base: '魔弹', desc: '将自身纹章的魔力直接推出的纯放出。便宜快速，无副作用。', tags: ['纯放出', '低耗', '速射'] },
      'bind|none': { base: '固化', desc: '将魔力高密度凝固为屏障。维持丝线可回收（G）返还部分魔力。', tags: ['固化', '屏障', '可回收'] },
      'divide|none': { base: '分解', desc: '解开异纹的结构。剥离结界与反力，瓦解术式造出的墙。', tags: ['剥离', '破坏结构', '克制结界'] },
      'convert|none': { base: '吸夺', desc: '改写所触魔力的纹章，夺为己有的魔素。', tags: ['夺取魔素', '续战', '低威力'] },
      'grow|none': { base: '修复', desc: '以自身纹章的魔力填补崩坏的结构。', tags: ['回复', '支援', '转换损耗'] },
      'phase|none': { base: '相位化', desc: '瞬间错开自身相位，穿过紧接着的攻击。', tags: ['回避', '无敌时间', '低威力'] },
      'bind|motion': { base: '惯性拘束', desc: '束缚想要移动的力，持续将目标拉回中心。', tags: ['拘束', '拉回', '地形系留'] },
      'divide|grow': { base: '腐蚀孢子', desc: '分解作用自我增殖，化为侵蚀接触面的毒性领域。', tags: ['毒', '持续侵蚀', '扩散'] },
      'bind|grow': { base: '根缚', desc: '结合向地下增殖，从脚下钉住目标。', tags: ['定身', '根墙', '生成地形'] },
      'motion|motion': { base: '共振冲击', desc: '使双重运动同步，从接触点呈环状释放冲击。', tags: ['冲击波', '击飞', '破碎'] },
      'convert|grow': { base: '生体转写', desc: '将夺来的魔素化为可增殖的结构，定着为回复场。', tags: ['吸收', '再生', '领域维持'] },
      'bind|phase': { base: '相位牢', desc: '将目标的相位结合于空间，封住越界的行动。', tags: ['隔离', '封锁', '防御'] },
      'divide|phase': { base: '虚蚀', desc: '只分解物质的相位边界，无视防壁侵入。', tags: ['贯通', '无视防壁', '高负荷'] },
      'motion|phase': { base: '转位穿孔', desc: '让相位先行至运动的落点，使术式与施术者跃迁。', tags: ['转移', '贯通', '奇袭'] },
      'convert|divide': { base: '崩坏转换', desc: '将分解的结构转为不稳定的魔素，连同地形一起崩毁。', tags: ['腐蚀', '破坏地形', '回收魔素'] },
      'convert|motion': { base: '反力转换', desc: '将受到的运动转为魔素，朝反方向放出。', tags: ['反射', '吸收', '反击'] },
      'grow|motion': { base: '连锁波', desc: '运动每次传播都会增殖出下一道波，连锁至多处。', tags: ['连锁', '波及', '面压制'] },
      'bind|convert': { base: '物性编壁', desc: '重新结合周围地形，筑起改变性质的屏障。', tags: ['防壁', '利用地形', '变质'] },
      'divide|motion': { base: '断裂刃', desc: '分解运动的轨迹本身，撕裂通过线上的一切。', tags: ['切断', '直线', '破甲'] },
      'grow|phase': { base: '重层镜界', desc: '增殖相位，展开多个施术者的影像分散攻击。', tags: ['分身', '回避', '扰乱'] },
      'bind|bind': { base: '重缚结界', desc: '双重闭合结合，编织包覆自身的减伤结界。', tags: ['防御', '支援', '减伤'] },
      'convert|phase': { base: '相位转换', desc: '改写受到的术式相位，化为施术者的魔素。', tags: ['回收魔素', '无效化', '重构'] },
      'grow|grow': { base: '增殖苗床', desc: '增殖唤起增殖，自行移动的碎片追踪目标。', tags: ['追踪', '数量压制', '持续'] },
      'phase|phase': { base: '相干观测', desc: '叠合相位，读取所触目标的结构值（耐久·魔素）。', tags: ['观测', '情报', '低威力'] },
      'convert|convert': { base: '魔素收束', desc: '叠加转换，将魔素之流束于一点，形成吸引周围魔素的井。', tags: ['聚集魔素', '回复效率', '设置'] },
      'bind|divide': { base: '掘削堑壕', desc: '撕开结合向下挖掘，筑起可藏身的壕沟。遮断射线。', tags: ['遮蔽', '生成地形', '防御'] },
      'divide|divide': { base: '解体领域', desc: '解开一切结合。地形与术式皆被同等解体。', tags: ['解除术式', '破坏地形', '高负荷'] }
    },
    presets: {
      bolt: { label: '纯放出（1部件）' }, shock: { label: '共振冲击针' }, guided: { label: '丝线诱导' }, beam: { label: '贯通光线' }, remote: { label: '远程起爆' }, solid: { label: '固化盾（可回收）' }, wall: { label: '物性编壁' }, barrier: { label: '魔力屏障' },
      blades: { label: '环绕刃（固体）' }, spear: { label: '晶枪（固体）' }, shuriken: { label: '手里剑（固体）' }, katana: { label: '斩光（日本刀）' }, axe: { label: '破城斧（固体）' }, chakram: { label: '圆月轮（固体）' }, arrow: { label: '光矢（三连）' }, bastion: { label: '石墙（面状固体结界）' },
      castle: { label: '城塞（环绕城墙）' }, aegis: { label: '完全结界' }, reflect: { label: '反射' }, shift: { label: '无效化' }, poison: { label: '腐蚀陷阱' }, blink: { label: '转位穿孔' }, well: { label: '魔素收束' }, mend: { label: '自我修复' },
      haste: { label: '加速（强化术）' }, harden: { label: '硬化（强化术）' }, vital: { label: '活性（强化术）' }, heavy: { label: '9部件重术式' }
    },
    schools: [
      { name: '光芒射手', spells: [{ customName: '流星' }, { customName: '天穿' }, { customName: '砦' }, { customName: '疾风' }] },
      { name: '剑圣', spells: [{ customName: '胧斩' }, { customName: '八重樱' }, { customName: '缩地' }, { customName: '大镰·宵薙' }] },
      { name: '城塞之主', spells: [{ customName: '破城' }, { customName: '金城' }, { customName: '绝界' }, { customName: '地鸣' }] },
      { name: '咒术师', spells: [{ customName: '瘴气之种' }, { customName: '缚锁' }, { customName: '噬魂' }, { customName: '虚空穿刺' }] },
      { name: '爆破师', spells: [{ customName: '爆缚阵' }, { customName: '崩天' }, { customName: '散华' }, { customName: '反转' }] },
      { name: '驭群者', spells: [{ customName: '千本樱' }, { customName: '三叉雷' }, { customName: '夺魂域' }, { customName: '再生' }] },
      { name: '雷帝', spells: [{ customName: '雷枪' }, { customName: '天雷' }, { customName: '雷鸣环' }, { customName: '魔素收束' }] },
      { name: '镜之魔女', spells: [{ customName: '月轮' }, { customName: '镜花' }, { customName: '水镜' }, { customName: '惯性之锁' }] }
    ],
    rooms: { ichi: { name: '一之间', note: '标准大小。适合第一次参战' }, sema: { name: '狭间', note: '狭窄，很快就会交火' }, oo: { name: '大广间', note: '宽广。坚持到成长壮大' }, dojo: { name: '修炼场', note: '以人偶试验自创的术。不留记录' } },
    dummies: [{ name: '人偶·静' }, { name: '人偶·走' }, { name: '人偶·墙' }, { name: '人偶·射' }, { name: '人偶·炮' }],
    tiers: [{ name: '无纹' }, { name: '初纹' }, { name: '二纹' }, { name: '三纹' }, { name: '四纹' }, { name: '五纹' }, { name: '纹匠' }, { name: '纹圣' }],
    inks: { pink: { name: '蔷薇' }, blue: { name: '苍' }, yellow: { name: '金' }, green: { name: '嫩叶' }, orange: { name: '焰' }, purple: { name: '紫' }, teal: { name: '翠' }, red: { name: '红' } },
    crests: { ring: '圆', bar: '圆中一', cross: '十字', lozenge: '菱', igeta: '井桁', scale: '鳞', stars: '三星', wheel: '连环' },
    cries: {
      win: ['胜利不是证明，而是下一个问题的开始。', '刻在这纹章上的，不是胜者之名，而是选择。', '此刻，我把消散的力量化为了守护。', '我赢了。可被我毁掉的东西回不来了。', '并非看透一切，只是跨过了一个迷惘。', '所谓强大，是懂得不去毁掉什么。', '系上丝线的手与斩断它的手，是同一双手。', '连胜利之后的寂静，我也一并承受。', '不是器量之差，而是我坚持重新选择到了最后。', '这一胜，不会是终点。', '领教异纹的差距吧。', '结束了。', '太慢了。', '散吧。', '归于灰烬。'],
      death: ['……纹章松开了。直到最后，我都是我。', '器物虽碎，所选之路不会消失……', '消散的魔力，也有归处……', '没能守护的东西，我也不会忘记……', '这场败北，也将成为下一个结构的一部分……', '丝线断了。再也无法托付给谁……', '胜利并不是唯一的正确……', '生命会消散。但愿望仍在……', '看错的不是术式，是我的恐惧……', '直到最后一片，意志也不交出……', '呃……啊啊啊！', '……到此为止了吗。', '可恶……被黑暗吞没……', '不可能……我竟会……', '不甘……']
    },
    defaultCries: { win: '看见了吗，这就是纹章之力！', death: '可恶……还不能在这里消散……！' },
    howto: [['移动', 'WASD / 方向键'], ['切换术', '1·2·3·4 / 滚轮 / 点击下方栏位'], ['施术', '鼠标瞄准，左键（按住连续咏唱）'], ['闪避', '右键 / Space'], ['指令起爆', 'F（向「发动：指令」的术发送信号）'], ['回收', 'G（解开「丝线：维持」的术，返还部分魔力）'], ['术式台', 'T（修炼场中、大厅、消散后）'], ['声音', 'M 音效，N 音乐，V 语音（无／仅技名／技名与呐喊），B 切换曲目。详细设置见大厅的「设置」']],
    rules: [
      '在「术式台」构筑术。选择发生什么（原理）、什么形状、如何送达、何时发生、之后如何，就会成为27种现象之一。',
      '部件越多，消耗与咏唱越重，威力也越低。部件少的朴素术式最省魔力、一击最重。可驾驭的部件数（控制容量）随等级成长：LV0为4、LV3为5、LV7为7、LV12为9。超过的术在施放瞬间可能暴发。',
      '术以「固体」或「能量」放出。能量贯穿固体结界，固体剥离能量结界，同质相互阻挡。让固体环绕，刃会在周身旋转，既是盾也是武器。',
      '放出的术飞得越远越消散变弱。光线与枪几乎不衰减。形状（针·矢·剑·日本刀·大镰·斧·锤·手里剑·圆月轮·枪·城…）会改变速度、判定与对结界的贯穿力。',
      '「完全」结界叠合固体与能量，什么都无法通过。但消耗极大，展开期间魔力持续减少、行动迟缓，咏唱术时即解除。',
      '异纹的术在空中相撞。固体相撞弱者碎裂，能量相互抵消，能量贯穿固体时大幅减弱且固体也被削去。炸裂的冲击会吹散异纹的能量弹，弹开固体弹。光线会烧尽异纹的能量弹。',
      '自己纹章的术不会相斥，而是相互叠合。能量相遇「融合」为更大的一发，能量碰到自己的固体弹会「魔装」使其更重。穿过自己能量场的弹与光线会「共鸣」增强，炸裂会「诱爆」附近自己的陷阱。自己的结界放行自己的术（可隔墙射击）。接住圆月轮可返还一半魔力。',
      '战场地面的六个纹章是「六原理节点」。站在圈内，含该原理的术威力提升、消耗降低，魔力也会涌出。站在中央的「要之阵」控制容量 +1。',
      '自创的术可在「修炼场」以人偶试验。修炼场中随时按 T 重新构筑。',
      '在战场上拾取地面的光粒（魔素）即可成长并回复魔力。魔力不会自动回复（只在六原理节点内涌出）。魔素就是分数。被击散的对手会撒出魔素，你还能夺取其魔力。',
      '消散即结束。分数与名次会化为位阶点数。可立即重新进入。'
    ],
    chant: {
      a: { motion: '疾驰吧', bind: '结合，凝固', divide: '解开吧', convert: '流转，归还', grow: '萌发，充盈', phase: '相位，摇曳' },
      b: { motion: '撕裂风', bind: '重叠束缚', divide: '劈开理', convert: '改写纹章', grow: '延续生命', phase: '穿越暗影', none: '' },
      behavior: { project: '', homing: '勿令逃脱', lob: '倾泻而下', sow: '化为种子', drop: '存于此处', orbit: '环绕于我', relay: '贯穿三方', beam: '贯穿' },
      form: { point: '', line: '', plane: '化为墙', ring: '化为环', field: '充满吧' },
      deploy: { single: '', burst: '爆裂吧', scatter: '散开', linger: '留下', sprinkle: '撒下', siphon: '夺取' }
    }
  }
};

// ═══ 한국어 ═════════════════════════════════════════════════════
LANG.ko = {
  ui: {
    '・': ' · ', '！': '!', '／': ' / ', '{0}{1}。': '{0} {1}. ',
    '加速': '가속', '硬化': '경화', '活性': '활성', '自分の紋の魔力を体へ書き込んだ': '자신의 문장의 마력을 몸에 새겼다',
    '暴発': '폭발', '「{0}」は制御容量を超えていた': '「{0}」이(가) 제어 용량을 넘었다', '術式が…崩れる！': '술식이… 무너진다!',
    '結界崩壊': '결계 붕괴', '貫通': '관통', '剥離': '박리', '「{0}」の節点': '「{0}」의 절점',
    '{0}を含む術が強まり（威力 ×{1}・消費 ×{2}）、輪の中では魔力が湧き出る': '{0}을(를) 포함한 술이 강해지고(위력 ×{1}·소모 ×{2}), 고리 안에서는 마력이 솟는다',
    '要の陣': '요의 진', 'ここに立つ間は制御容量が +{0}。重い術を暴発させずに扱える': '여기 서 있는 동안 제어 용량 +{0}. 무거운 술도 폭발 없이 다룰 수 있다',
    '共鳴': '공명', '相殺': '상쇄', '融合': '융합', '魔装': '마장', '誘爆': '유폭',
    '完全結界が解けた': '완전 결계가 풀렸다', '魔力が尽きた': '마력이 바닥났다', '術を唱えると解ける': '술을 외우면 풀린다',
    '+{0} 魔力': '+{0} 마력', '糸が切れた': '실이 끊어졌다', '術者から離れすぎた': '술자에게서 너무 멀어졌다', '糸を断たれた': '실이 잘렸다',
    '回収 +{0} 魔力': '회수 +{0} 마력', '糸でつながった術式 {0} つをほどいた': '실로 이어진 술식 {0}개를 풀었다', '構造崩壊': '구조 붕괴',
    '{0} を散らした': '{0}을(를) 흩어버렸다', '+{0} 魔素': '+{0} 마소',
    '制御容量が {0} になった。より重い術を安定して放てる': '제어 용량이 {0}이(가) 되었다. 더 무거운 술을 안정적으로 쓸 수 있다', '次の制御容量まで育て': '다음 제어 용량까지 성장하라',
    '曲を変えた': '곡을 바꿨다', '声なし': '음성 없음', '技名だけ': '기술명만', '技名と叫び': '기술명과 외침', '声：{0}': '음성: {0}',
    '要の陣 ― 制御容量 +{0}': '요의 진 ― 제어 용량 +{0}', '{0}の節点 ― {0}の術が強まり、魔力が湧く': '{0}의 절점 ― {0}의 술이 강해지고, 마력이 솟는다',
    '{0}人': '{0}명', 'LV {0}・制御容量 {1}': 'LV {0} · 제어 용량 {1}', '（LV{0}で{1}）': ' (LV{0}에서 {1})',
    '魔力 {0}': '마력 {0}', '部品 {0}/{1}': '부품 {0}/{1}', '・暴発 {0}%': ' · 폭발 {0}%', '糸 {0}': '실 {0}', 'F 指示起爆（{0}）': 'F 지시 기폭({0})', 'G 回収': 'G 회수',
    '与えた威力 {0}・毎秒 {1}': '준 피해 {0} · 초당 {1}', '受けた威力 {0}・防いだ {1}': '받은 피해 {0} · 막음 {1}', '攻撃人形：撃つ': '공격 인형: 발사', '攻撃人形：止める': '공격 인형: 정지',
    '{0} に散らされた': '{0}에게 흩어졌다', '結界の外で散った': '결계 밖에서 흩어졌다', '{0} が結界に散った': '{0}이(가) 흩어졌다',
    '攻撃人形が撃ちはじめた': '공격 인형이 쏘기 시작했다', '攻撃人形を止めた': '공격 인형을 멈췄다', '受けた威力と、結界で防いだ数を数える（修練場では散らない）': '받은 피해와 결계로 막은 횟수를 센다(수련장에서는 흩어지지 않는다)',
    '技': '기', '声': '음', '声：{0}（V で切り替え）': '음성: {0} (V로 전환)', '自動（ブラウザに合わせる）': '자동(브라우저에 맞춤)', '　◆自然': '  ◆자연', '（日本語の声が見つからない）': '(이 언어의 음성을 찾을 수 없음)',
    '首位　{0}　{1}': '1위  {0}  {1}', '次の「{0}」まで {1} pt': '「{0}」까지 {1} pt', '最上位の位階': '최상위 위계', '{0}位': '{0}위', '撃破 {0}': '격파 {0}',
    '<li class="empty">まだ入場していない</li>': '<li class="empty">아직 입장 기록이 없다</li>', '部品 {0}・魔力 {1}': '부품 {0} · 마력 {1}', '原理負荷 {0}': '원리 부하 {0}', 'なし': '없음',
    '単一原理（純放出）。最も軽く速い': '단일 원리(순방출). 가장 가볍고 빠르다', '負荷 {0}・半径 {1}': '부하 {0} · 반경 {1}', '自動': '자동', '広がり方から決める（弾は針、細い波は結晶、ほかは球）': '퍼짐 방식으로 결정(작은 탄은 침, 가는 파동은 결정, 나머지는 구)',
    '{0}（速さ×{1}・当たり×{2}・威力×{3}・結界へ×{4}{5}）': '{0}(속도×{1} · 판정×{2} · 위력×{3} · 결계에×{4}{5})', '・形作る負荷 {0}': ' · 형태 부하 {0}',
    '作例「{0}」を {1} に読み込んだ': '예시 「{0}」을(를) {1}번에 불러왔다', '流派「{0}」の4つの術を読み込んだ（{1}）': '유파 「{0}」의 술 4개를 불러왔다({1})', '{0}の「{1}」を {2} に読み込んだ': '{0}의 「{1}」을(를) {2}번에 불러왔다', '初期の4つに戻した': '초기 4개로 되돌렸다',
    'まっすぐ飛ばす': '곧게 날린다', '放ち、違う紋の大きな魔力へ曲がらせる': '날려서 다른 문장의 큰 마력 쪽으로 휘게 한다', '放物線で狙った地点へ落とす': '포물선으로 노린 지점에 떨어뜨린다', '足元近くへ転がして止める': '발밑 근처로 굴려 멈춘다',
    '自分の足元に置く': '자기 발밑에 둔다', '自分の周りに纏う': '자기 주위에 두른다', '三方へ撃ち分ける': '세 방향으로 나눠 쏜다', '一直線の光にして貫く': '일직선의 빛으로 꿰뚫는다',
    '触れた瞬間に': '닿는 순간', '殻が割れる時（時限）に': '껍질이 깨질 때(시한)', '違う紋が近づいた時に': '다른 문장이 다가올 때', 'F の合図で': 'F 신호로',
    '一度作用する': '한 번 작용한다', '大きく炸裂する': '크게 작렬한다', '追尾する小片に分かれる': '추적하는 파편으로 갈라진다', 'その場に領域として残る': '그 자리에 영역으로 남는다', '攻撃せずに魔力の粒と囮を撒く': '공격하지 않고 마력 알갱이와 미끼를 뿌린다', '領域の中の敵から魔力と魔素を奪い続ける': '영역 안의 적에게서 마력과 마소를 계속 빼앗는다',
    '強化術：自分の紋の魔力を体へ書き込み、{0}。': '강화술: 자신의 문장의 마력을 몸에 새겨 {0}.', '動きを速くする（加速）': '움직임을 빠르게 한다(가속)', '受ける威力を減らす（硬化）': '받는 피해를 줄인다(경화)', '体力を少しずつ戻す（活性）': '체력을 조금씩 회복한다(활성)',
    '完全：固体とエネルギーを重ね、どちらの質も光線も通さない。引き換えに、張っている間は魔力が戻らず毎秒減り、足が重く、術を唱えると解ける。': '완전: 고체와 에너지를 겹쳐 어떤 질도 광선도 통과시키지 않는다. 대신 펼친 동안 마력이 회복되지 않고 매초 줄며, 발이 무거워지고, 술을 외우면 풀린다.',
    '{0}枚の城壁で自分をぐるりと囲む（ほとんど回らない）。弾を受け止める壁になる': '{0}장의 성벽으로 자신을 빙 둘러싼다(거의 돌지 않는다). 탄을 막는 벽이 된다',
    '{0}本の{1}を自分の周りに回らせる。弾を受け止め、触れた相手を斬る': '{1} {0}자루를 자기 주위로 돌린다. 탄을 막고, 닿은 상대를 벤다', '刃': '칼날',
    '「{0}」を固体にして、{1}。': '「{0}」을(를) 고체로 만들어 {1}. ', 'エネルギーの弾は貫いてくる。エネルギーの結界は剥がせる。': '에너지 탄은 뚫고 들어온다. 에너지 결계는 벗겨낼 수 있다. ', '糸でつながり、回収（G）できる。': '실로 이어져 회수(G)할 수 있다. ',
    '「{0}」を{1}。': '「{0}」: {1}. ', '{0}の「{1}」を{2}{3}。': '{0}의 「{1}」 — {2}{3}. ', '固体（結晶）にして': '고체(결정)로 만들어 ', 'エネルギーのまま': '에너지 그대로 ',
    '周りに入った違う紋に{0}。': '주위에 들어온 다른 문장에 {0}. ', '作用し続ける': '계속 작용한다',
    '固体の結界には止められるが、エネルギーの結界は剥がせる。': '고체 결계에는 막히지만, 에너지 결계는 벗겨낼 수 있다. ', '固体の結界は貫けるが、エネルギーの結界には止められる。': '고체 결계는 뚫지만, 에너지 결계에는 막힌다. ',
    '六枚の面の壁で囲む城壁になる。': '여섯 면의 벽으로 둘러싼 성벽이 된다. ', '一枚の面の壁になる。': '한 장의 면 벽이 된다. ', '形：{0}。': '형태: {0}. ',
    '放った後も糸でつながり、誘導・指示起爆（F）・回収（G）ができる（維持費がかかる）。': '날린 뒤에도 실로 이어져 유도·지시 기폭(F)·회수(G)가 가능하다(유지비가 든다). ', '追加性質：{0}。': '추가 성질: {0}. ',
    '貫通光線は「細い波・接触・単発・糸：切断」で固定': '관통 광선은 「가는 파동·접촉·단발·실: 절단」으로 고정', '貫通光線は光そのもの。質は「エネルギー」だけ': '관통 광선은 빛 그 자체. 질은 「에너지」뿐',
    '完全は結界を作る術（固化・物性編壁・掘削塹壕・根絡・位相牢・重縛結界・位相転換・反力変換）と周回にだけ使える': '완전은 결계를 만드는 술(고화·물성 편벽·굴삭 참호·뿌리얽기·위상 감옥·중박 결계·위상 전환·반력 변환)과 주회에만 쓸 수 있다',
    '周回は常に起動しているので「接触」だけ': '주회는 항상 기동 중이라 「접촉」만', '周回の追加機能は「単発・残留・吸魔」だけ': '주회의 추가 기능은 「단발·잔류·흡마」만', '指示起爆は糸を通して合図を送るので「維持」が必要': '지시 기폭은 실로 신호를 보내므로 「유지」가 필요',
    '部品 {0}': '부품 {0}', '{0}（押すと外す）': '{0}(누르면 제거)', 'なし（最大{0}つ・重複可）': '없음(최대 {0}개·중복 가능)', '現象：{0}': '현상: {0}', '{0}秒': '{0}초', '純度 ×{0}（部品が少ないほど重い）': '순도 ×{0}(부품이 적을수록 강하다)',
    'LV{0}〜 容量{1}': 'LV{0}~ 용량{1}', '・安定': ' · 안정', '決定して試す': '결정하고 시험', '修練場で試す': '수련장에서 시험', '糸{0}': '실 {0}', '名無し': '이름 없음',
    '人形を相手に術を試す。T で術式台、Esc で戻る': '인형을 상대로 술을 시험한다. T로 술식대, Esc로 돌아간다', '術を放つと入場保護が解ける': '술을 쓰면 입장 보호가 풀린다', '左をなぞって歩く': '왼쪽을 쓸어 이동', '右をタッチして放つ': '오른쪽을 터치해 발사', '下の枠で持ち替え': '아래 칸으로 교체',
    '左クリック': '왼쪽 클릭', '放つ': '발사', '持ち替え': '교체', '回避': '회피', '退出': '퇴장', '歩く': '걷기', '魔導士を動かしてみよう。': '마도사를 움직여 보자.', '矢印キー': '방향키', '画面の左半分をなぞる': '화면 왼쪽 절반을 쓸기', '術を放つ': '술 발사',
    'マウスで狙い、左クリックで術を放つ。押し続けると続けて唱える。放つたびに魔力（青い帯）を使う。戦場では魔力は勝手に戻らず、光の粒（魔素）を拾うと戻る。': '마우스로 조준하고 왼쪽 클릭으로 술을 쓴다. 누르고 있으면 계속 외운다. 쓸 때마다 마력(파란 막대)을 소모한다. 전장에서는 마력이 저절로 돌아오지 않으며, 빛 알갱이(마소)를 주우면 돌아온다.',
    'マウスで狙う': '마우스로 조준', '画面の右半分をタッチ': '화면 오른쪽 절반을 터치', '人形に当てる': '인형 맞히기', '近くの人形に術を当てよう。当てた威力は上の「与えた威力」に出る。': '가까운 인형에 술을 맞혀 보자. 준 피해는 위의 「준 피해」에 표시된다.', '人形の方をタッチ': '인형 쪽을 터치',
    '術を持ち替える': '술 교체', '術は4つまで持てる。2〜4に持ち替えて放ってみよう。4の「物性編壁」は相手の術を止める壁になる。': '술은 4개까지 들 수 있다. 2~4로 바꿔서 써 보자. 4번 「물성 편벽」은 상대의 술을 막는 벽이 된다.', 'ホイール': '휠', '下の枠をクリック': '아래 칸 클릭', '下の枠をタッチ': '아래 칸 터치',
    '一瞬だけ素早く跳んで、飛んでくる術をかわす（魔力を少し使う）。': '한순간 재빨리 뛰어 날아오는 술을 피한다(마력을 조금 쓴다).', '右クリック': '오른쪽 클릭', '回避ボタン': '회피 버튼', '術を組む': '술 짜기',
    '術式台で原理と部品をつないで、自分の術を作る。名前を付けると、放つときにその技名を叫ぶ。開いて「決定」で閉じよう。': '술식대에서 원리와 부품을 이어 자신의 술을 만든다. 이름을 붙이면 쓸 때 그 기술명을 외친다. 열고 「결정」으로 닫아 보자.', 'T で術式台': 'T로 술식대', '決定 / Esc': '결정 / Esc', '上の「術式台」ボタン': '위의 「술식대」 버튼', '準備はできた': '준비 완료',
    '戦場では地面の魔素を拾うと育ち、相手を散らすとその魔素を奪える。育つほど制御容量が増え、重い術も暴発させずに扱える。装いも格が上がる。魔力は光の粒を拾うと戻る。散ったらすぐ入りなおせる。': '전장에서는 땅의 마소를 주우면 성장하고, 상대를 흩어버리면 그 마소를 빼앗을 수 있다. 성장할수록 제어 용량이 늘어 무거운 술도 폭발 없이 다룬다. 차림새도 격이 오른다. 마력은 빛 알갱이를 주우면 돌아온다. 흩어지면 바로 다시 들어갈 수 있다.',
    '修練場に残る': '수련장에 남기', '手ほどきを終える': '튜토리얼 종료', '結界の外で構造が崩れた': '결계 밖에서 구조가 무너졌다', '{0}・計 {1} pt': '{0} · 합계 {1} pt', '表示で問題が起きた': '화면에 문제가 생겼다', 'このまま遊べるが、続くときは再読み込みしてほしい': '계속 플레이할 수 있지만, 계속되면 새로고침해 주세요',
    '光のにじみを切った': '빛 번짐을 껐다', '動きが重かったため。設定で戻せる': '동작이 무거워서. 설정에서 되돌릴 수 있다', 'PRIMA 紋戦': 'PRIMA 문전', 'このゲームは JavaScript で動きます。ブラウザの設定で JavaScript を有効にしてください。': '이 게임은 JavaScript로 동작합니다. 브라우저 설정에서 JavaScript를 켜 주세요.',
    '魔素': '마소', '撃破': '격파', '一の間': '첫째 방', '手ほどき': '튜토리얼', '戦場へ入る': '전장 입장', '構造': '구조', '魔力': '마력', '避': '피', '修練場': '수련장', '与えた威力 0': '준 피해 0', '受けた威力 0・防いだ 0': '받은 피해 0 · 막음 0', '術式台': '술식대', 'ロビーへ': '로비로',
    '音': '음', '曲': '곡', '設': '설', '紋戦': '문전', '原理を接続して術を組み、乱戦で放て。': '원리를 이어 술을 짜고, 난전에서 쏴라.', 'はじめての方へ': '처음이신 분께', '修練場で、動き方・術の放ち方・術の組み方を実際にやってみる（3分ほど）。': '수련장에서 이동, 술 쓰기, 술 짜기를 직접 해 본다(약 3분).',
    '手ほどきを始める': '튜토리얼 시작', '名前': '이름', '光の色': '빛의 색', '紋': '문장', '丸': '원', 'ルーム': '방', '戦場の参加者はいまはBotです。オンライン対戦は準備中。': '현재 전장의 참가자는 봇입니다. 온라인 대전은 준비 중.', '遊び方': '플레이 방법', '設定（声・音・画面）': '설정(음성·소리·화면)',
    '術': '술', '術式台を開く': '술식대 열기', '勝利宣言': '승리 선언', '倒したときに叫ぶ': '쓰러뜨렸을 때 외친다', '断末魔': '단말마', '散ったときに叫ぶ': '흩어졌을 때 외친다', '声で試す': '음성으로 시험', '無': '無', '無紋': '무문',
    '次の位階まで 250 pt': '다음 위계까지 250 pt', '最高魔素': '최고 마소', '最高順位': '최고 순위', '通算撃破': '누적 격파', '入場': '입장', '最近の入場': '최근 입장', '散った': '흩어졌다', '生存': '생존', '位階が上がった': '위계 상승', 'もう一度入る': '다시 입장', '術式を組み直す': '술식 다시 짜기',
    '原理と部品を接続して、1〜4 の枠に術を組む。部品が増えるほど消費と詠唱が重くなり、制御容量を超えると暴発しうる。': '원리와 부품을 이어 1~4번 칸에 술을 짠다. 부품이 늘수록 소모와 영창이 무거워지고, 제어 용량을 넘으면 폭발할 수 있다.',
    '決定': '결정', '何が起こる': '무엇이 일어나나', '主原理': '주원리', 'もう一つの性質': '또 하나의 성질', '副原理': '부원리', '形': '형태', '広がり方': '퍼짐 방식', 'どう届く': '어떻게 닿나', '届き方': '전달 방식', 'いつ起こる': '언제 일어나나', '発動': '발동', '起きた後': '일어난 뒤', '追加機能': '추가 기능',
    '放った後': '쏜 뒤', '糸': '실', '上乗せ': '덧붙이기', '追加性質': '추가 성질', '強': '강', '強弱': '강약', '威力': '위력', '時限・持続': '시한·지속', '連射': '연사', '質': '질', '固めるか': '굳힐까', '固体／エネルギー': '고체 / 에너지', '刃の形': '칼날 형태', '速さ・当たり・衰え': '속도·판정·감쇠',
    '空欄なら現象の名前。付けると放つときに唱える': '비우면 현상의 이름. 붙이면 쓸 때 외친다', '魔弾針': '마탄 침', '部品': '부품', '詠唱': '영창', '遠くで': '먼 곳에서', '制御容量と暴発': '제어 용량과 폭발', '部品にふれると、その意味がここに出る': '부품에 마우스를 올리면 여기에 설명이 나온다',
    '達人の流派': '달인의 유파', 'Bot が修める4つの術を丸ごと読み込む': '봇이 익힌 술 4개를 통째로 불러온다', '達人の術': '달인의 술', '作例': '예시', '初期の4つに戻す': '초기 4개로 되돌리기', '六原理（単一原理で放つと）': '여섯 원리(단일 원리로 쓰면)', '閉じる': '닫기', '設定': '설정', '言語': '언어',
    '名前を付けた術を放つとき、その技名を叫ぶ。「技名と叫び」は勝利宣言と断末魔も声に出す。': '이름 붙인 술을 쓸 때 그 기술명을 외친다. 「기술명과 외침」은 승리 선언과 단말마도 소리 낸다.', '声の種類': '음성 종류', '試す': '시험', '「Natural」「Online」と付いた声がいちばん人に近い（Edge・Chrome で使える）。': '「Natural」「Online」이 붙은 음성이 가장 사람에 가깝다(Edge·Chrome에서 사용 가능).',
    '効果音': '효과음', '音楽': '음악', '曲を変える': '곡 바꾸기', '光のにじみ': '빛 번짐', '術の光がまわりへにじむ。重いときは切る': '술의 빛이 주위로 번진다. 무거우면 끈다',
    '原理を接続して自分の術を組み、ルームの乱戦で放つ。魔素を拾い、散らして奪い、散ったらすぐ入りなおす魔法の乱戦。': '원리를 이어 자신의 술을 짜고, 방 전체의 난전에서 쏜다. 마소를 줍고, 흩어버려 빼앗고, 흩어지면 바로 다시 들어가는 마법 난전.', 'PRIMA 紋戦 — 術を組み、乱戦で放て': 'PRIMA 문전 — 술을 짜고, 난전에서 쏴라',
    '原理をつないで自分だけの魔法を組み、魔導士の乱戦で放つブラウザゲーム。登録不要・すぐ遊べる。': '원리를 이어 나만의 마법을 짜고 마도사들의 난전에서 쏘는 브라우저 게임. 가입 없이 바로 플레이.', '戦場': '전장', '自分の状態': '내 상태', '順位': '순위', '体と刻印': '몸', '回避（右クリック / Space）': '회피(오른쪽 클릭 / Space)',
    '射（槍・魔弾・日本刀・手裏剣）と砲（光線・斧）の人形が撃ってくる': '사수 인형(창·마탄·일본도·수리검)과 포수 인형(광선·도끼)이 공격해 온다', '全体図': '전체 지도', '効果音（M）': '효과음(M)', '音楽（N）': '음악(N)', '声（V）': '음성(V)', 'ロビーへ戻る（Esc）': '로비로 돌아가기(Esc)', '術と叫び': '술과 외침', '位階': '위계', '術の枠': '술 칸', '術の動きの見本': '술 움직임 미리보기', '（自動）': '(자동)'
  },
  data: {
    naming: { join: ' ', extraSep: ' · ', beam: '{0} 관통 광선', beamStrip: ' 칼날', shapeSuffix: { needle: '침', orb: '탄', shard: '결정', arrow: '화살', blade: '검', katana: '태도', scythe: '낫', axe: '도끼', hammer: '망치', shuriken: '별', chakram: '륜', spear: '창', castle: '성' } },
    principles: { motion: { name: '운동' }, bind: { name: '결합' }, divide: { name: '분해' }, convert: { name: '변환' }, grow: { name: '증식' }, phase: { name: '위상' } },
    noPrinciple: { name: '없음' },
    forms: { point: { name: '작은 탄', suffix: '침' }, line: { name: '가는 파동', suffix: '맥' }, plane: { name: '벽', suffix: '벽' }, ring: { name: '주위', suffix: '환' }, field: { name: '넓은 장', suffix: '역' } },
    behaviors: {
      project: { name: '사출', note: '직진한다. 바위와 결계에 막힌다. 멀수록 위력이 흩어진다' }, homing: { name: '추적', note: '다른 문장의 큰 마력 쪽으로 휜다. 실을 유지하면 조준점으로 유도할 수 있다' },
      lob: { name: '투사', note: '포물선으로 결계와 바위를 넘는다. 착지점이 예고된다' }, sow: { name: '파종', note: '발밑 근처에 씨앗을 뿌린다. 굴러가 멈추고 함정이 된다' },
      drop: { name: '제자리', note: '지금 있는 곳에 설치한다' }, orbit: { name: '주회', note: '술자를 따라다니며 항상 기동한다. 단일 원리면 강화술. 고체로 하면 칼날이 주위를 돈다' },
      relay: { name: '부채 사격', note: '세 방향으로 나눠 쏜다. 흩어지기 쉽다' }, beam: { name: '관통 광선', note: '적을 꿰뚫는 고출력 광선. 멀리서도 거의 약해지지 않는다. 고체 결계는 뚫고, 에너지 결계도 강하면 부순다' }
    },
    triggers: { contact: { name: '접촉', note: '명중·접촉 시 기동' }, fuse: { name: '시한', note: '껍질이 흩어져 깨지는 순간 기동(사출은 조준점에서 작렬)' }, proximity: { name: '감지', note: '다른 문장이 범위에 들어오면 기동. 멈춘 술식은 함정이 된다' }, command: { name: '지시', note: '실을 통한 신호로 기동(F). 실은 자동으로 유지된다' } },
    deploys: { single: { name: '단발', note: '퍼짐 방식대로 한 번 작용한다' }, burst: { name: '작렬', note: '범위를 넓혀 한순간에 작렬한다' }, scatter: { name: '분열', note: '추적하는 파편으로 갈라진다' }, linger: { name: '잔류', note: '영역이 오래 남는다' }, sprinkle: { name: '산마', note: '공격하지 않고 소모를 마력 알갱이로 뿌린다. 누구나 주울 수 있고 추적의 미끼가 된다' }, siphon: { name: '흡마', note: '영역 안 적의 마력과 마소를 빼앗고 주위 마소를 술자에게 끌어온다. 위력 절반' } },
    links: { cut: { name: '절단', note: '쏘는 순간 실을 끊는다. 유지비 없음. 술식대로만 움직인다' }, hold: { name: '유지', note: '실로 계속 이어진다. 유지비가 들지만 유도·지시 기폭(F)·연장·회수(G)가 가능' } },
    extraEffects: { motion: { note: '명중 시 넉백 추가' }, bind: { note: '명중 시 둔화. 두 번 겹치면 잠시 속박' }, divide: { note: '결계·껍질을 벗기고 위력 +8%' }, convert: { note: '명중 시 상대의 마력을 빼앗는다' }, grow: { note: '명중 시 추적 파편을 낳는다' }, phase: { note: '결계·경화의 감쇠를 덜 받는다' } },
    matters: { energy: { name: '에너지', note: '빛과 열 그대로 쏜다. 빠르지만 멀리서 흩어지기 쉽다. 고체 결계를 뚫고, 에너지 결계에 막힌다' }, solid: { name: '고체', note: '결정으로 굳혀 쏜다. 느리지만 무겁고 잘 약해지지 않는다. 에너지 결계를 벗기고, 고체 결계에 막힌다. 고체 결계는 매우 단단하다' }, perfect: { name: '완전', note: '고체와 에너지를 겹친 완전한 결계. 아무것도 통과시키지 않는다. 다만 소모가 매우 크고, 펼친 동안 마력이 계속 줄며 발이 무거워지고, 술을 외우면 풀린다(결계·주회만)' } },
    shapes: {
      needle: { name: '침', note: '가늘고 빠르다. 판정이 작다' }, orb: { name: '구', note: '크고 맞히기 쉽지만 조금 느리다' }, shard: { name: '결정', note: '뾰족한 결정. 결계에 조금 강하다' }, arrow: { name: '화살', note: '가장 가늘고 빠른 화살. 판정은 아주 작지만 멀리 닿는다' },
      blade: { name: '검', note: '폭이 넓은 직검. 판정이 크고 묵직하지만 멀리서는 무뎌진다' }, katana: { name: '일본도', note: '휜 칼날. 한 명을 베고 지나가 뒤의 상대에게도 닿는다' }, scythe: { name: '큰낫', note: '호를 그리는 큰 칼날. 판정이 가장 넓고 세 명까지 벤다. 사거리가 짧다' },
      axe: { name: '도끼', note: '무거운 도끼. 느리지만 한 방이 무겁고 결계를 쪼갠다' }, hammer: { name: '망치', note: '거대한 망치. 결계에 가장 강하고 상대를 크게 날려 보낸다' }, shuriken: { name: '수리검', note: '회전하는 네 날의 별. 바위나 결계에 맞으면 두 번까지 튕긴다' },
      chakram: { name: '원월륜', note: '회전하는 고리. 멀리 날아가면 손으로 돌아오며 돌아올 때도 맞는다' }, spear: { name: '창', note: '긴 창끝. 가장 덜 약해지고 결계를 뚫는 힘이 강하다' }, castle: { name: '성', note: '돌로 쌓은 성벽. 쏘면 느리고 무거운 덩어리, 주회시키면 거의 돌지 않는 성벽이 자신을 두른다' }
    },
    visualShapes: { auto: '자동', needle: '침', orb: '구', shard: '결정', arrow: '화살', blade: '검', katana: '일본도', scythe: '큰낫', axe: '도끼', hammer: '망치', shuriken: '수리검', chakram: '원월륜', spear: '창', castle: '성' },
    pairData: {
      'motion|none': { base: '마탄', desc: '자신의 문장의 마력을 그대로 밀어내는 순방출. 싸고 빠르지만 부작용은 없다.', tags: ['순방출', '저연비', '속사'] },
      'bind|none': { base: '고화', desc: '마력을 고밀도로 굳혀 장벽을 만든다. 실을 유지하면 회수(G)로 마력 일부가 돌아온다.', tags: ['고화', '장벽', '회수 가능'] },
      'divide|none': { base: '분해', desc: '다른 문장의 구조를 푼다. 결계·반력을 벗기고 술식으로 만든 벽을 무너뜨린다.', tags: ['박리', '구조 파괴', '대결계'] },
      'convert|none': { base: '흡탈', desc: '닿은 마력의 문장을 고쳐 써서 자신의 마소로 빼앗는다.', tags: ['마소 탈취', '지구전', '저위력'] },
      'grow|none': { base: '수복', desc: '자신의 문장의 마력으로 무너진 구조를 메운다.', tags: ['회복', '지원', '변환 손실'] },
      'phase|none': { base: '위상화', desc: '자신의 위상을 한순간 어긋나게 해 바로 다음 공격을 흘려보낸다.', tags: ['회피', '무적 시간', '저위력'] },
      'bind|motion': { base: '관성 구속', desc: '움직이려는 힘을 묶어 중심으로 계속 끌어당긴다.', tags: ['구속', '끌어당김', '지형 계류'] },
      'divide|grow': { base: '부식 포자', desc: '분해 작용이 자기 증식해 닿는 면을 좀먹는 독성 영역이 된다.', tags: ['독', '지속 침식', '확산'] },
      'bind|grow': { base: '뿌리얽기', desc: '결합이 땅속으로 증식해 발밑에서 대상을 꿰매 둔다.', tags: ['발묶기', '뿌리 벽', '지형 생성'] },
      'motion|motion': { base: '공진 충격', desc: '이중의 운동을 동조시켜 접촉점에서 충격을 원형으로 해방한다.', tags: ['충격파', '날려보내기', '파쇄'] },
      'convert|grow': { base: '생체 전사', desc: '빼앗은 마소를 증식 가능한 구조로 바꿔 회복장으로 정착시킨다.', tags: ['흡수', '재생', '영역 유지'] },
      'bind|phase': { base: '위상 감옥', desc: '대상의 위상을 공간에 결합해 경계를 넘는 움직임을 봉한다.', tags: ['격리', '경계 봉쇄', '방어'] },
      'divide|phase': { base: '허식', desc: '물질의 위상 경계만 분해해 방벽을 무시하고 침투한다.', tags: ['관통', '방벽 무시', '고부하'] },
      'motion|phase': { base: '전위 천공', desc: '운동의 도착점으로 위상을 앞세워 술식과 술자를 도약시킨다.', tags: ['전이', '관통', '기습'] },
      'convert|divide': { base: '붕괴 변환', desc: '분해한 구조를 불안정한 마소로 바꿔 지형째 무너뜨린다.', tags: ['부식', '지형 파괴', '마소 회수'] },
      'convert|motion': { base: '반력 변환', desc: '받은 운동을 마소로 바꿔 반대 방향으로 방출한다.', tags: ['반사', '흡수', '반격'] },
      'grow|motion': { base: '연쇄파', desc: '운동이 퍼질 때마다 다음 파동을 증식시켜 여러 지점으로 연쇄한다.', tags: ['연쇄', '파급', '면 제압'] },
      'bind|convert': { base: '물성 편벽', desc: '주위 지형을 다시 결합해 성질을 바꾼 장벽을 쌓는다.', tags: ['방벽', '지형 이용', '변질'] },
      'divide|motion': { base: '단열 칼날', desc: '운동의 궤적 자체를 분해해 지나가는 선 위를 찢는다.', tags: ['절단', '직선', '장갑 관통'] },
      'grow|phase': { base: '중층 경계', desc: '위상을 증식시켜 술자의 상을 여럿 펼쳐 공격을 분산시킨다.', tags: ['분신', '회피', '교란'] },
      'bind|bind': { base: '중박 결계', desc: '결합을 이중으로 닫아 자신을 감싸는 감쇠 결계를 엮는다.', tags: ['방어', '지원', '감쇠'] },
      'convert|phase': { base: '위상 전환', desc: '받은 술식의 위상을 고쳐 써서 술자의 마소로 되돌린다.', tags: ['마소 회수', '무효화', '재구성'] },
      'grow|grow': { base: '증식 묘상', desc: '증식이 증식을 부르고, 스스로 움직이는 파편이 대상을 추적한다.', tags: ['추적', '물량 압박', '지속'] },
      'phase|phase': { base: '상간 관측', desc: '위상을 겹쳐 닿은 대상의 구조값(내구·마소)을 읽는다.', tags: ['관측', '정보', '저위력'] },
      'convert|convert': { base: '마소 수속', desc: '변환을 겹쳐 마소의 흐름을 한 점으로 묶어 주위 마소를 끌어당기는 우물을 만든다.', tags: ['마소 집속', '회복 효율', '설치'] },
      'bind|divide': { base: '굴삭 참호', desc: '결합을 찢어 땅을 파내 몸을 숨길 도랑을 만든다. 사선을 끊는다.', tags: ['엄폐', '지형 생성', '방어'] },
      'divide|divide': { base: '해체 영역', desc: '모든 결합을 푼다. 지형도 술식도 똑같이 풀린다.', tags: ['술식 해제', '지형 파괴', '고부하'] }
    },
    presets: {
      bolt: { label: '순방출(1부품)' }, shock: { label: '공진 충격 침' }, guided: { label: '실로 유도' }, beam: { label: '관통 광선' }, remote: { label: '원격 기폭' }, solid: { label: '고화 방패(회수 가능)' }, wall: { label: '물성 편벽' }, barrier: { label: '마력 배리어' },
      blades: { label: '주회 칼날(고체)' }, spear: { label: '결정 창(고체)' }, shuriken: { label: '수리검(고체)' }, katana: { label: '참광(일본도)' }, axe: { label: '파성 도끼(고체)' }, chakram: { label: '원월륜(고체)' }, arrow: { label: '빛 화살(3연)' }, bastion: { label: '돌벽(면 고체 결계)' },
      castle: { label: '성채(주회 성벽)' }, aegis: { label: '완전 결계' }, reflect: { label: '반사' }, shift: { label: '무효화' }, poison: { label: '부식 함정' }, blink: { label: '전위 천공' }, well: { label: '마소 수속' }, mend: { label: '자기 수복' },
      haste: { label: '가속(강화술)' }, harden: { label: '경화(강화술)' }, vital: { label: '활성(강화술)' }, heavy: { label: '9부품 중술식' }
    },
    schools: [
      { name: '광망의 사수', spells: [{ customName: '유성' }, { customName: '천천' }, { customName: '보루' }, { customName: '질풍' }] },
      { name: '검성', spells: [{ customName: '몽롱참' }, { customName: '겹벚꽃' }, { customName: '축지' }, { customName: '큰낫·어스름베기' }] },
      { name: '성채의 주인', spells: [{ customName: '파성' }, { customName: '금성' }, { customName: '절계' }, { customName: '지명' }] },
      { name: '주술사', spells: [{ customName: '장기의 씨앗' }, { customName: '박쇄' }, { customName: '영혼 포식' }, { customName: '공허 관통' }] },
      { name: '폭파사', spells: [{ customName: '폭박진' }, { customName: '붕천' }, { customName: '산화' }, { customName: '반전' }] },
      { name: '무리 부리는 자', spells: [{ customName: '천본앵' }, { customName: '삼지뢰' }, { customName: '탈혼역' }, { customName: '재생' }] },
      { name: '뇌제', spells: [{ customName: '뇌창' }, { customName: '천뢰' }, { customName: '뇌명환' }, { customName: '마소 수속' }] },
      { name: '거울의 마녀', spells: [{ customName: '월륜' }, { customName: '경화' }, { customName: '수경' }, { customName: '관성의 사슬' }] }
    ],
    rooms: { ichi: { name: '첫째 방', note: '표준 크기. 첫 입장에 알맞다' }, sema: { name: '틈새', note: '좁아서 금세 교전이 벌어진다' }, oo: { name: '대광간', note: '넓다. 크게 자랄 때까지 살아남아라' }, dojo: { name: '수련장', note: '인형을 상대로 만든 술을 시험한다. 기록은 남지 않는다' } },
    dummies: [{ name: '인형·정지' }, { name: '인형·보행' }, { name: '인형·벽' }, { name: '인형·사수' }, { name: '인형·포수' }],
    tiers: [{ name: '무문' }, { name: '초문' }, { name: '이문' }, { name: '삼문' }, { name: '사문' }, { name: '오문' }, { name: '문장인' }, { name: '문성' }],
    inks: { pink: { name: '장미' }, blue: { name: '창' }, yellow: { name: '금' }, green: { name: '새잎' }, orange: { name: '불꽃' }, purple: { name: '보라' }, teal: { name: '비취' }, red: { name: '진홍' } },
    crests: { ring: '원', bar: '원에 한 일', cross: '십자', lozenge: '마름모', igeta: '우물 정', scale: '비늘', stars: '세 별', wheel: '엇갈린 고리' },
    botNames: ['Vesper', 'Ashen', 'Noctis', 'Morrow', 'Grave', 'Umbra', 'Sable', 'Wraith', 'Cinder', 'Hollow', 'Rook', 'Crow', 'Ember', 'Lament', 'Requiem', 'Vigil', 'Shroud', 'Obsidian', 'Thorn', 'Omen',
      '잿빛', '흑요', '그믐', '까마귀깃', '먹물', '장송', '명등', '초토', '백골', '땅거미', '잔향', '안개비', '절영', '무명', '동월', '창염', '황혼', '단죄', '침묵', '고영'],
    cries: {
      win: ['승리는 증명이 아니다. 다음 질문의 시작이다.', '이 문장에 새기는 것은 승자의 이름이 아니라 선택이다.', '흩어지는 힘을, 지금만은 지키는 형태로 만들었다.', '이겼다. 그래도 부순 것은 돌아오지 않는다.', '다 읽어낸 게 아니다. 망설임 하나를 넘었을 뿐.', '강함이란 무엇을 부수지 않고 끝낼지 아는 것.', '실을 묶는 손도 끊는 손도 같은 손이었다.', '승리 뒤에 남는 고요까지 떠안겠다.', '그릇의 차이가 아니다. 끝까지 다시 고른 차이다.', '이 한 번의 승리를 끝으로 삼지 않겠다.', '다른 문장의 차이를 깨달아라.', '끝이다.', '느리다.', '흩어져라.', '재로 돌아가라.'],
      death: ['……문장이 풀린다. 끝까지 나였다.', '그릇은 부서져도 고른 길은 사라지지 않는다……', '흩어지는 마력에도 돌아갈 곳이 있다……', '지키지 못한 것까지 잊지 않겠다……', '이 패배도 다음 구조의 일부가 된다……', '실이 끊겼다. 이제 누구에게도 맡길 수 없다……', '이기는 것만이 옳음은 아니었다……', '생명은 흩어진다. 그래도 바람은 남는다……', '잘못 본 건 술식이 아니다. 나의 두려움이다……', '마지막 한 조각까지 의지는 넘기지 않는다……', '크윽…… 아아악!', '……여기까지인가.', '큭…… 어둠에 삼켜진다……', '말도 안 돼…… 이 내가……', '원통하다……']
    },
    defaultCries: { win: '보았느냐, 이것이 문장의 힘이다!', death: '큭… 아직 흩어질 수는…!' },
    howto: [['이동', 'WASD / 방향키'], ['술 교체', '1·2·3·4 / 휠 / 아래 칸 클릭'], ['술 쓰기', '마우스로 조준, 왼쪽 클릭(누르고 있으면 계속 영창)'], ['회피', '오른쪽 클릭 / Space'], ['지시 기폭', 'F(「발동: 지시」인 술에 신호를 보낸다)'], ['회수', 'G(「실: 유지」인 술을 풀어 마력 일부를 되돌린다)'], ['술식대', 'T(수련장 안, 로비, 흩어진 뒤)'], ['소리', 'M 효과음, N 음악, V 음성(없음/기술명만/기술명과 외침), B 곡 바꾸기. 자세한 설정은 로비의 「설정」']],
    rules: [
      '술은 「술식대」에서 짠다. 무엇이 일어나는지(원리)·어떤 형태인지·어떻게 닿는지·언제 일어나는지·일어난 뒤 어떻게 되는지를 고르면 27가지 현상 중 하나가 된다.',
      '부품이 늘수록 소모와 영창이 무거워지고 위력도 떨어진다. 부품이 적은 단순한 술일수록 연비가 좋고 한 방이 무겁다. 다룰 수 있는 부품 수(제어 용량)는 레벨로 자란다: LV0에서 4, LV3에서 5, LV7에서 7, LV12에서 9. 넘는 술은 쓰는 순간 폭발할 수 있다.',
      '술은 「고체」나 「에너지」로 쏜다. 에너지는 고체 결계를 뚫고, 고체는 에너지 결계를 벗긴다. 같은 질끼리는 막힌다. 고체를 주회시키면 칼날이 주위를 돌며 방패도 무기도 된다.',
      '쏜 술은 멀리 갈수록 흩어져 약해진다. 광선과 창은 거의 약해지지 않는다. 형태(침·화살·검·일본도·큰낫·도끼·망치·수리검·원월륜·창·성…)에 따라 속도·판정·결계 관통력이 달라진다.',
      '「완전」 결계는 고체와 에너지를 겹쳐 아무것도 통과시키지 않는다. 다만 소모가 매우 크고, 펼친 동안 마력이 계속 줄며 발이 무거워지고, 술을 외우면 풀린다.',
      '다른 문장의 술끼리는 공중에서 부딪친다. 고체끼리는 충돌해 약한 쪽이 부서지고, 에너지끼리는 상쇄하며, 에너지가 고체를 뚫으면 크게 약해지고 고체도 깎인다. 작렬의 폭풍은 다른 문장의 에너지 탄을 날려 끄고 고체 탄을 튕겨낸다. 광선은 다른 문장의 에너지 탄을 태워 없앤다.',
      '자기 문장의 술끼리는 반발하지 않고 겹친다. 에너지끼리는 「융합」해 큰 한 발이 되고, 에너지가 자신의 고체 탄에 닿으면 「마장」으로 고체가 무거워진다. 자신의 에너지 장을 지난 탄과 광선은 「공명」해 강해지고, 작렬은 근처의 자기 함정을 「유폭」시킨다. 자신의 결계는 자신의 술을 통과시킨다(벽 너머로 쏠 수 있다). 원월륜을 받아내면 마력이 절반 돌아온다.',
      '전장 바닥의 여섯 문장은 「여섯 원리의 절점」. 그 고리 안에 서면 그 원리를 포함한 술의 위력이 오르고 소모가 줄며 마력이 솟는다. 중앙의 「요의 진」에 서면 제어 용량이 1 늘어난다.',
      '만든 술은 「수련장」에서 인형을 상대로 시험할 수 있다. 수련장에서는 T로 언제든 다시 짤 수 있다.',
      '전장에서는 땅의 빛 알갱이(마소)를 주우면 성장하고 마력도 돌아온다. 마력은 저절로 돌아오지 않는다(여섯 원리의 절점 안에서만 솟는다). 마소가 곧 점수다. 흩어진 상대의 마소는 주위에 뿌려지고 마력도 빼앗을 수 있다.',
      '흩어지면 끝. 점수와 순위가 위계 포인트가 된다. 바로 다시 들어갈 수 있다.'
    ],
    chant: {
      a: { motion: '재빨리 달려라', bind: '맺고, 굳어라', divide: '풀려라', convert: '흘러, 돌아가라', grow: '싹트고, 차올라라', phase: '위상이여, 흔들려라' },
      b: { motion: '바람을 가르고', bind: '속박을 겹치고', divide: '이치를 쪼개고', convert: '문장을 고쳐 쓰고', grow: '생명을 잇고', phase: '그림자를 건너', none: '' },
      behavior: { project: '', homing: '놓치지 마라', lob: '쏟아져라', sow: '씨앗이 되어라', drop: '여기 있어라', orbit: '나를 돌아라', relay: '세 방향을 꿰뚫어라', beam: '꿰뚫어라' },
      form: { point: '', line: '', plane: '벽이 되어라', ring: '고리가 되어라', field: '가득 차라' },
      deploy: { single: '', burst: '터져라', scatter: '흩어져라', linger: '머물러라', sprinkle: '뿌려라', siphon: '빼앗아라' }
    }
  }
};

(typeof window !== 'undefined' ? window : globalThis).PRIMA_LANG = LANG;
})();
